### ISSUE TITLE
Добавление параметров в операцию после выбора операции

### ISSUE THREAD

**Issue by dimabeel** [savushkin-r-d/EasyEPLANner#105]
Сейчас, если мы добавляем в объект параметры, и внутри объекта пишем, какой операции он принадлежит, то после того, как мы указали операцию, параметр не записывается в операцию. Сейчас это работает, только если после того, как будут настроены все параметры закрыть/открыть проект.
Выбранный параметр должен добавиться в операцию (если его нет), или при смене операции, он должен удалиться из старой операции (если он там был), и добавиться в новую (если его не было).

Остальная реализация (перебор, при переносе операции вверх/вниз, удалении и др. будет сделан в другой раз т.к будет осуществлен перевод с индексного способа взаимодействия с параметрами к именному).

**Comment by idzm** [comment]
Также параметры могут относится более чем к одной операции - тогда операции указываются через пробел.
