### ISSUE TITLE
Орфографические ошибки в документе EasyEPLANner/docs/user_manual/ReadMe.md

### ISSUE THREAD

**Issue by fakehomer** [savushkin-r-d/EasyEPLANner#1078]
Слово "бачок" написано неправильно два раза подряд.  
![image](https://user-images.githubusercontent.com/92292715/207293011-e0a6b917-dd29-4365-8eaf-d875f057ba2c.png)  
Ссылка на документ с ошибками:  
https://github.com/savushkin-r-d/EasyEPLANner/blob/master/docs/user_manual/ReadMe.md

**Comment by KirillGutyrchik** [comment]
Сойздайте fork проекта, внесите изменения в файл и создайте pull-request.

**Comment by fakehomer** [comment]
> Создайте fork проекта, внесите изменения в файл и создайте pull-request. Сделал
