### ISSUE TITLE
Ошибки в тексте

### ISSUE THREAD

**Issue by MikMaks** [savushkin-r-d/EasyEPLANner#1079]
Обнаружил пару орфографических и пунктуационных ошибок, а именно: "которого", вместо "которых" (т.к. от словосочетания "набор соглашений"), "чтобы" слитно, а также должна быть запятая перед "чтобы".
![image](https://user-images.githubusercontent.com/75979457/207392247-fbe29901-074b-427a-8c98-161517ea51c8.png)
Ссылка на файл с данными ошибками:  https://github.com/savushkin-r-d/EasyEPLANner/tree/master/docs/ru

**Comment by KirillGutyrchik** [comment]
Сойздайте fork проекта, внесите изменения в файл и создайте pull-request.

**Comment by MikMaks** [comment]
#1097 сделал
