### ISSUE TITLE
Орфографические ошибки в тексте

### ISSUE THREAD

**Issue by Vlad-203** [savushkin-r-d/EasyEPLANner#1085]
Слово "инженер-программист" написано неверно.

Предложение "В конечном итоге EasyEPLANner генерирует LUA файлы, которые загружаются в контроллер",
пунктуационно написано неверно.

Ссылка на документ с ошибками: https://github.com/savushkin-r-d/EasyEPLANner/blob/master/docs/ru/readme.md

**Comment by idzm** [comment]
Необходимо создать `fork` проекта, внести изменения в файл и создать `pull-request`.
