### ISSUE TITLE
Орфографические ошибки

### ISSUE THREAD

**Issue by NastyaBokatyik** [savushkin-r-d/EasyEPLANner#1089]
Пункт 4.1 написано "так-же" по правилам "также" является производным союзом и должно писаться слитно.
Пункт 5.1 написано "находится". Операция может делать что? Исходя из правил русского языка, когда мы задаём вопрос с "ть", то глагол тоже должен писаться с мягким знаком: "находиться".
Пункт 4 написано "что бы". Должно быть написано "чтобы", т.к это союзное слово в спп предложении.

Ссылка на файл:

https://github.com/savushkin-r-d/EasyEPLANner/blob/master/docs/user_manual/ReadMe.md

**Comment by KirillGutyrchik** [comment]
Необходимо создать fork проекта, внести изменения в файл и создать pull-request.

**Comment by NastyaBokatyik** [comment]
создала fork проекта, внесла изменения в файл и создада pull-request
