### ISSUE TITLE
Ошибки и опечатки в документации

### ISSUE THREAD

**Issue by 1Nick10** [savushkin-r-d/EasyEPLANner#1090]
Слово "вырезать" некорректно взято в кавычки.
![image](https://user-images.githubusercontent.com/91867777/208657451-2f9538b4-d766-43d8-a24e-0ec7cf18a88c.png)
Отсутствует запятая перед "... в который...".
![image](https://user-images.githubusercontent.com/91867777/208658015-3c9ab632-d207-40a5-81f7-ef0924d41ea6.png)
Опечатка в слове "их".
![image](https://user-images.githubusercontent.com/91867777/208658099-8bff307f-cca0-4724-8e01-c3b284473691.png)

**Comment by 1Nick10** [comment]
Ссылка на документ: 
https://github.com/savushkin-r-d/EasyEPLANner/blob/master/docs/user_manual/ReadMe.md

**Comment by KirillGutyrchik** [comment]
Необходимо создать fork проекта, внести изменения в файл и создать pull-request.
