### ISSUE TITLE
Орфографические ошибки в EasyEPLANner/docs/user_manual/ReadMe.md

### ISSUE THREAD

**Issue by dima203** [savushkin-r-d/EasyEPLANner#1095]
1. После запятой перед следующим словом нужен пробел.
![image](https://user-images.githubusercontent.com/44814540/209437084-95381ca2-381e-4176-acc0-513cdb481bb1.png)
2. Ошибка в слове "теги"
![image](https://user-images.githubusercontent.com/44814540/209437268-9db63e7b-6427-48d4-8557-c92816f8b72b.png)
3. Пропущена запятая после слова "Value"
![image](https://user-images.githubusercontent.com/44814540/209437356-995dbabf-af8c-44b2-9209-229cfc92aad0.png)
4. Пропущен дефис, должно быть "2-х"
![image](https://user-images.githubusercontent.com/44814540/209437397-584ae9d2-e8bf-4ab2-b0df-2b51f43a0c01.png)

**Comment by KirillGutyrchik** [comment]
Необходимо создать fork проекта, внести изменения в файл и создать pull-request.
