### ISSUE TITLE
Шаги из "Выполнения" переместились в "Простой"

### ISSUE THREAD

**Issue by AndreyNemenkov** [savushkin-r-d/EasyEPLANner#1108]
Шаги из "Выполнения" переместились в "Простой"
![image](https://user-images.githubusercontent.com/65279645/212017544-162bf400-4dd9-4368-b876-983760bfa5ee.png)
Такое наблюдается во всех объектах.

**Comment by idzm** [comment]
Это было из-за версии дополнения, которая содержала ошибку работы с состояниями операции. В текущей крайней версии всё работает корректно.
