### ISSUE TITLE
Возможность отключать в настройках автозакрытие EPLAN при неактивности пользователя

### ISSUE THREAD

**Issue by idzm** [savushkin-r-d/EasyEPLANner#1126]
Реализовать возможность через настройки управлять работой модуля контроля активности пользователя.

**Comment by idzm** [comment]
Возможно потребуется доработать функциональность - закрывать открытый проект, но не закрывать **EPLAN**. @AndreyNemenkov - что скажешь?

**Comment by AndreyNemenkov** [comment]
> Возможно потребуется доработать функциональность - закрывать открытый проект, но не закрывать **EPLAN**. @AndreyNemenkov - что скажешь?
Я уверен, что лучше не закрывать проект вообще, мне не очень понравилось, что я не мог открыть проект после "автоматического закрытия", до тех пор, пока его не открыли на разблокированном ПК, не через удаленное подключение. На сетевом диске мы работаем каждый со своим проектом, если кто-то, что-то хочет посмотреть в твоем проекте, он просто копирует его себе локально. Открытый проект не мешает его копировать.
