### ISSUE TITLE
Проблема с открытием обмена сигналов для проектов типа шлюз

### ISSUE THREAD

**Issue by KUZMA-1989** [savushkin-r-d/EasyEPLANner#1175]
При открытии проектов, в которых есть обмен типа DO->DO, DI->DI и т.д, то не открывается межконтроллерный обмен

**Comment by KirillGutyrchik** [comment]
@KUZMA-1989.
В файле описания межпроектного обмена необходимо, чтобы группы сигналов соответсвовали противоположным подтипам.
Чтобы описание прочиталось корректно, необходимо вручную в связанном проекте заменить названия груп на противоположные:
![image](https://github.com/savushkin-r-d/EasyEPLANner/assets/88157888/7d83c873-a11d-4f34-85c4-289d070cac57)
![image](https://github.com/savushkin-r-d/EasyEPLANner/assets/88157888/55167b67-ea8e-4ea0-9e59-8c22961e3b8f)

Также ссылка на документацию про ручной перевод обмена для работы в Eplanner: [13 Ручная доработка старого обмена сигналами в новый](https://github.com/savushkin-r-d/EasyEPLANner/blob/master/docs/user_manual/InterprojectExchange.md#13-Ручная-доработка-старого-обмена-сигналами-в-новый)

Также, чтобы включить в интерфейсе надстройки привязку сигналов одинакового типа (DO->DO), необходимо в параметрах фильра отключить контроль пар сигналов:
![image](https://github.com/savushkin-r-d/EasyEPLANner/assets/88157888/60822e00-0094-4132-b537-eefb7f54c6dd)

**Comment by KUZMA-1989** [comment]
@

> @KUZMA-1989. В файле описания межпроектного обмена необходимо, чтобы группы сигналов соответсвовали противоположным подтипам. Чтобы описание прочиталось корректно, необходимо вручную в связанном проекте заменить названия груп на противоположные: ![image](https://user-images.githubusercontent.com/88157888/243654395-7d83c873-a11d-4f34-85c4-289d070cac57.png) ![image](https://user-images.githubusercontent.com/88157888/243657093-55167b67-ea8e-4ea0-9e59-8c22961e3b8f.png)
> 
> Также ссылка на документацию про ручной перевод обмена для работы в Eplanner: [13 Ручная доработка старого обмена сигналами в новый](https://github.com/savushkin-r-d/EasyEPLANner/blob/master/docs/user_manual/InterprojectExchange.md#13-%D0%A0%D1%83%D1%87%D0%BD%D0%B0%D1%8F-%D0%B4%D0%BE%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%BA%D0%B0-%D1%81%D1%82%D0%B0%D1%80%D0%BE%D0%B3%D0%BE-%D0%BE%D0%B1%D0%BC%D0%B5%D0%BD%D0%B0-%D1%81%D0%B8%D0%B3%D0%BD%D0%B0%D0%BB%D0%B0%D0%BC%D0%B8-%D0%B2-%D0%BD%D0%BE%D0%B2%D1%8B%D0%B9)
> 
> Также, чтобы включить в интерфейсе надстройки привязку сигналов одинакового типа (DO->DO), необходимо в параметрах фильра отключить контроль пар сигналов: ![image](https://user-images.githubusercontent.com/88157888/243656530-60822e00-0094-4132-b537-eefb7f54c6dd.png)

@KirillGutyrchik На картинках описания в документации графически выделить изменения, которые нужно внести, для большей наглядности.
