### ISSUE TITLE
Сброс привязанных агрегатов к операции

### ISSUE THREAD

**Issue by KUZMA-1989** [savushkin-r-d/EasyEPLANner#1182]
Когда меняешь базовую операцию в уже описанной, то сделать сообщение "Сбрасывать привязанные агрегаты" если "Да", то сбрасываем привязанные агрегаты и параметры для них, если "Нет", то всё привязанное оставляем.

**Comment by KirillGutyrchik** [comment]
@KUZMA-1989, необходимо полностью сбрасывать всю привязку для объекта или только доп.свойства агрегатов для данной опирации?

**Comment by KUZMA-1989** [comment]
> @KUZMA-1989, необходимо полностью сбрасывать всю привязку для объекта или только доп.свойства агрегатов для данной опирации?

Только в той операции сброс доп свойств, которую меняешь

**Comment by KUZMA-1989** [comment]
> @KUZMA-1989, необходимо полностью сбрасывать всю привязку для объекта или только доп.свойства агрегатов для данной опирации?

Только доп свойства
