### ISSUE TITLE
Привязка несуществующих параметров к доп. полям

### ISSUE THREAD

**Issue by KUZMA-1989** [savushkin-r-d/EasyEPLANner#1190]
Когда привязываем параметры в операциях объекта в доп.поля, то если в этом объекте не существует параметр с таким именем, то дополнительное поле, куда мы прописали несуществующее имя параметра, должно очиститься. 
А сейчас параметр в поле остаётся и в prg экспортируется неправильный код привязки.

**Comment by KirillGutyrchik** [comment]
@KUZMA-1989, сбрасывать данное поле при сохранении или достаточно в логах указать, что поле заполнено неверно?

**Comment by KUZMA-1989** [comment]
> @KUZMA-1989, сбрасывать данное поле при сохранении или достаточно в логах указать, что поле заполнено неверно?

Лучше сбросить
