### ISSUE TITLE
Переименовать подписи к функционалу шагов

### ISSUE THREAD

**Issue by KUZMA-1989** [savushkin-r-d/EasyEPLANner#1198]
![image](https://github.com/savushkin-r-d/EasyEPLANner/assets/56631906/3f14bbd3-e156-4a05-9c9c-afd159d90216)

**Comment by KUZMA-1989** [comment]
@KirillGutyrchik Добавь в этот pullrequest и вот это 
![image](https://github.com/savushkin-r-d/EasyEPLANner/assets/56631906/2ee2aeb3-7272-4f00-8b96-65cc50d1cd2a)

**Comment by idzm** [comment]
Для большей информативности предлагаю использовать такие названия:
`Сигнал для включения шага` -> `Сигнал для включения данного шага`;
`Перейти в шаг по условию` -> `Переход к другому шагу по условию`.

@KUZMA-1989, @AndreyNemenkov - что скажете?

**Comment by KUZMA-1989** [comment]
> Для большей информативности предлагаю использовать такие названия: `Сигнал для включения шага` -> `Сигнал для включения данного шага`; `Перейти в шаг по условию` -> `Переход к другому шагу по условию`.
> 
> @KUZMA-1989, @AndreyNemenkov - что скажете?

Можно так

**Comment by KUZMA-1989** [comment]
> Для большей информативности предлагаю использовать такие названия: `Сигнал для включения шага` -> `Сигнал для включения данного шага`; `Перейти в шаг по условию` -> `Переход к другому шагу по условию`.
> 
> @KUZMA-1989, @AndreyNemenkov - что скажете?

Обсудили в отделе, оставляем мои подписи : Сигнал для включения текущего шага, Переход к следующему шагу по условию
