### ISSUE TITLE
Ошибка порогового регулятора

### ISSUE THREAD

**Issue by AndreyNemenkov** [savushkin-r-d/EasyEPLANner#1204]
> "В выходе OUT_VALUE ПИД-регулятора **ZM51LTC1** задано некорректное устройство. Нужно указать **AO**, **VC**, **M** или другой **ПИД**-регулятор."

Появляется это сообщение при добавлении предельного регулятора (в выход указывал клапан - `V`).

**Comment by KirillGutyrchik** [comment]
@AndreyNemenkov, по документации [6.5 Работа с ПИД-регулятором](https://github.com/savushkin-r-d/EasyEPLANner/blob/master/docs/user_manual/ReadMe.md#65-работа-с-пид-регулятором) для свойства OUT_VALUE могут быть заданы только устройства с типами: AO, VC, M или C(ПИД-регулятор). Нужно добавить возможность так же подключения типа V?

**Comment by idzm** [comment]
Имеется в виду `C_THLD` - пороговый регулятор. Для него выход является дискретным устройством (любой клапан, насос).

**Comment by KirillGutyrchik** [comment]
@idzm, @AndreyNemenkov, помимо **DO**, **V** и **M**, какие еще устройства могут подключаться к выходу порогового регулятора, а также доступно ли каскадное подключение нескольких пороговых регуляторов в цепочку?

**Comment by idzm** [comment]
Каскадного регулирования не будет. По устройствам - здесь все те устройства, которые возможны для действия `"Включение"`.
