### ISSUE TITLE
Сброс привязанных параметров и объектов

### ISSUE THREAD

**Issue by KUZMA-1989** [savushkin-r-d/EasyEPLANner#1221]
Заменил в линии наполнения операцию "работа" на "наполнение", выскочило сообщение "сбросить доп свойства привязанных агрегатов?", нажал "Нет", а программа все равно всё сбросило:

![image](https://github.com/savushkin-r-d/EasyEPLANner/assets/56631906/f9107ce0-5b67-43cf-a52a-a11643b76c6e)
![image](https://github.com/savushkin-r-d/EasyEPLANner/assets/56631906/fcf61eb8-a9ff-43e1-af82-1ee1055fd3d8)

**Comment by KirillGutyrchik** [comment]
@KUZMA-1989, у вас в объекте нет привязанных агрегатов, данная функция работает только с их параметрами. Базовые шаги сбрасываются всегда по умолчанию, если их нужно также не сбрасывать, могу это добавить.

**Comment by KUZMA-1989** [comment]
> @KUZMA-1989, у вас в объекте нет привязанных агрегатов, данная функция работает только с их параметрами. Базовые шаги сбрасываются всегда по умолчанию, если их нужно также не сбрасывать, могу это добавить.

Да, добавь
