### ISSUE TITLE
Снимать флаг редактирования объектов

### ISSUE THREAD

**Issue by KUZMA-1989** [savushkin-r-d/EasyEPLANner#1245]
При закрытии поля редактирования описания технологических объектов, то нужно автоматически снимать флаг редактирования объектов.

**Comment by KUZMA-1989** [comment]
@KirillGutyrchik Не работает данный функционал, кнопка редактирования остается включенной при закрытии окна редактирования технологических объектов

**Comment by KirillGutyrchik** [comment]
@KUZMA-1989, раньше работал?

**Comment by KUZMA-1989** [comment]
> @KUZMA-1989, раньше работал?
Не проверял. Возможно, нет.
