### ISSUE TITLE
Ошибка при импорте объектов

### ISSUE THREAD

**Issue by SergeiSilakov** [savushkin-r-d/EasyEPLANner#1259]
**Опишите ошибку**
Ошибка при импорте объектов

**Как воспроизвести её**
Шаги для воспроизведения проблемы
При импортировании узла вылезла ошибка

**Скриншоты**
![image](https://github.com/savushkin-r-d/EasyEPLANner/assets/139815520/ee23ae73-530c-4a23-800f-f012b85f359b)

**Comment by KirillGutyrchik** [comment]
Связано с #1252.
