### ISSUE TITLE
Ошибка привязки ограничения в импортированном объекте

### ISSUE THREAD

**Issue by KUZMA-1989** [savushkin-r-d/EasyEPLANner#1322]
При импортировании объекта и последующем задании ограничений, то ограничения заполняются как для объекта 0
![Uploading image.png…]()

**Comment by KirillGutyrchik** [comment]
@KUZMA-1989, не подгрузилось изображение.

**Comment by KUZMA-1989** [comment]
> @KUZMA-1989, не подгрузилось изображение.

Уже и не подгрузится
