### ISSUE TITLE
Добавить новые изделия для клапан As-interface V_AS_MIXPROOF

### ISSUE THREAD

**Issue by KUZMA-1989** [savushkin-r-d/EasyEPLANner#1339]
Для клапана **V_AS_MIXPROOF** добавить новое изделие в программу **Think Top V70 AS-interface 3.0** (изделия в EPLAN называются **AL.9615-4000-11, AL.9615-4002-12**) Описание команд аналогично старым клапанам As-i **V_AS_MIXPROOF**

**Comment by rartem** [comment]
[thinktop-v50-and-v70-product-leaflet.pdf](https://github.com/savushkin-r-d/EasyEPLANner/files/14585590/thinktop-v50-and-v70-product-leaflet.pdf)
[think top.PDF](https://github.com/savushkin-r-d/EasyEPLANner/files/14585593/think.top.PDF)
Раньше у них походу не было подписано, где верхнее и где нижнее.

**Comment by KUZMA-1989** [comment]
> [thinktop-v50-and-v70-product-leaflet.pdf](https://github.com/savushkin-r-d/EasyEPLANner/files/14585590/thinktop-v50-and-v70-product-leaflet.pdf) [think top.PDF](https://github.com/savushkin-r-d/EasyEPLANner/files/14585593/think.top.PDF) Раньше у них походу не было подписано, где верхнее и где нижнее.

@rartem Для старых типов клапанов AS-i оставляем по старому описание, для новых нужно поменять команды для флипов седел

**Comment by idzm** [comment]
В EPLANner изменения не требуются - только в управляющей программе.
