### ISSUE TITLE
Привязка параметров к устройствам

### ISSUE THREAD

**Issue by SergeiSilakov** [savushkin-r-d/EasyEPLANner#1343]
При указании параметра производительности для устройства организовать проверку на его наличие. Ситуация: указываю параметр 55 а у объекта максимальное кол-во параметров 50.

**Comment by SergeiSilakov** [comment]
Проверять так же в полях групп "включение устройств с задержкой" и "выключении устройств с задержкой"

**Comment by KirillGutyrchik** [comment]
@SergeiSilakov, для поля "Производительность/задание" указывается lua-имя параметра, нет?

**Comment by SergeiSilakov** [comment]
@KirillGutyrchik да, в мс.

**Comment by SergeiSilakov** [comment]
@KirillGutyrchik номер параметра

**Comment by KirillGutyrchik** [comment]
@SergeiSilakov, странно, просто для этого поля можно устанавливать параметр через окно "Устройста, параметры объектов"
![image](https://github.com/savushkin-r-d/EasyEPLANner/assets/88157888/3c4efe71-104e-4786-99e9-8a0bfe6d0c3a)

**Comment by SergeiSilakov** [comment]
@KirillGutyrchik конечно, но при записи номера параметра без использования панели с параметрами объекта желательно добавить проверку.
