### ISSUE TITLE
Некорректное отображение устройств

### ISSUE THREAD

**Issue by AndreyNemenkov** [savushkin-r-d/EasyEPLANner#1348]
До этого убрал доп. поле 1 в устройствах танка сливок №1

![image](https://github.com/savushkin-r-d/EasyEPLANner/assets/65279645/46b1838f-df22-43ce-8caf-60a250482600)

![image](https://github.com/savushkin-r-d/EasyEPLANner/assets/65279645/e338e3df-67ad-4d2f-8acb-a36c6aebc246)

**Comment by KirillGutyrchik** [comment]
@AndreyNemenkov, доп. поле[1] в свойствах на ФСА?

**Comment by AndreyNemenkov** [comment]
> @AndreyNemenkov, доп. поле[1] в свойствах на ФСА?
Да, делало это на вот этой версии епланнера, после чего обновился до актуальной 
![image](https://github.com/savushkin-r-d/EasyEPLANner/assets/65279645/62556828-12d4-45a9-ab92-d3e50ec50306)
