### ISSUE TITLE
Ошибка с отображение в поле дополнительные сигналы

### ISSUE THREAD

**Issue by KUZMA-1989** [savushkin-r-d/EasyEPLANner#135]
Когда привязываешь сигнал в дополнительных сигналах через клик, то надпись сигнала в поле появляется только после того, как перещелкнешь на другое поле

**Comment by dimabeel** [comment]
@KUZMA-1989 
1. Нажал на поле
2. Нажал на объект на схеме
3. И только при смене поля он отобразился?

**Comment by KUZMA-1989** [comment]
да

**Comment by KUZMA-1989** [comment]
В линиях, в танках вроде норм

**Comment by dimabeel** [comment]
@KUZMA-1989 , так кроме линий и танка нигде же не работает больше. Или я что-то не понимаю в запросе? В линиях по 1 сигналу, в танке по 2 (для операции "Мойка"). А больше ничего и не реализовано

**Comment by KUZMA-1989** [comment]
Поправил коммент

**Comment by dimabeel** [comment]
Баг подтвержден. Буду исправлять
