### ISSUE TITLE
Проверять IP адреса

### ISSUE THREAD

**Issue by SergeiSilakov** [savushkin-r-d/EasyEPLANner#1356]
- [x] Проверять соответствия IP адресов в обмене сигналами при синхронизации и если будут не соответствия то отображать не соответствия в логе.
- [x] При синхронизации проверять на дублирование IP адресов устройств( например чтобы не было узлов с одним IP ).

**Comment by KirillGutyrchik** [comment]
@SergeiSilakov, что именно в обмене сигналами нужно проверять?

**Comment by SergeiSilakov** [comment]
@KirillGutyrchik IP адрес удалённого контроллера в файле shared источника, если shared текущего проекта( проект с которого делается "синхронизация и сохранение" ) заполнен, если проект с которого делается "синхронизация и сохранение" является приёмником и если есть файлы проекта с которым проверяем обмен(источник) - проверяем IP заданный в shared соответствует ли заданному в контроллере.
