### ISSUE TITLE
DI, DO, устройства и пары DI->DO, AI->AO в шагах

### ISSUE THREAD

**Issue by KUZMA-1989** [savushkin-r-d/EasyEPLANner#136]
Надо добавить DI,DO,устройства и пары DI->DO, AI->AO в шагах. В шагах мало функциональности, с нашим подходом работы через шаги это ограничивает работу через Eplan, эту функциональность приходится прописывать программисту в программе.

**Comment by dimabeel** [comment]
@KUZMA-1989 Эту функциональность можно сделать, но работать она будет только после того, как будет добавлена в управляющую программу. Сроки добавления в управляющую программу - неизвестно т.к этим занимаюсь не я. Вопрос добавления этого функционала в Eplan будет рассмотрен после закрытия текущих кейсов.

**Comment by idzm** [comment]
Это можно сделать, @dimabeel - добавляем.
