### ISSUE TITLE
Добавление нового устройства (блока питания) с IO-Link

### ISSUE THREAD

**Issue by SergeiSilakov** [savushkin-r-d/EasyEPLANner#1360]
[Описание](https://www.phoenixcontact.com/en-ie/products/power-supply-unit-trio3-ps-1ac-24dc-10-4c-iol-1252696) устройства.
Объединяет в себе два устройства: блок питания и автомат ([8233268.pdf](https://github.com/savushkin-r-d/EasyEPLANner/files/14975138/8233268.pdf)).
Основное обозначение в **EPLANner** будет `G`.
Основные свойства как на автомате **IO-Link**.
Связано с https://github.com/savushkin-r-d/ptusa_main/issues/685.

**Comment by idzm** [comment]
@SergeiSilakov - надо также сюда продублировать - https://github.com/savushkin-r-d/ptusa_main/issues.
