### ISSUE TITLE
Вывод сообщения об ошибке привязки клапанов с некорректным типом

### ISSUE THREAD

**Issue by KUZMA-1989** [savushkin-r-d/EasyEPLANner#1361]
Сейчас есть возможность привязать клапана типа
**V_DO1
V_DO2
V_DO1_DI1_FB_OFF
V_DO1_DI1_FB_ON
V_DO1_DI2
V_DO2_DI2**
к пневмооcтрову IO_LINK
**DEV_VTUG_8
DEV_VTUG_16 
DEV_VTUG_24**
Нужно сделать, чтоб не было возможности привязки каналов DO устройств к данным пневмоостровам. Или если они привязались, чтоб выдавалось сообщение о данном событии в логах проекта.
Соответственно и типы клапанов
**V_IOLINK_DO1_DI2
V_IOLINK_VTUG_DO1
V_IOLINK_VTUG_DO1_FB_OFF
V_IOLINK_VTUG_DO1_FB_ON
V_IOLINK_VTUG_DO1_DI2
V_IOL_TERMINAL_MIXPROOF_DO3
V_IOLINK_MIXPROOF**
нельзя привязывать к каналам модулей контроллера DO. Или если они привязались, чтоб выдавалось сообщение о данном событии в логах проекта.

**Comment by KirillGutyrchik** [comment]
@KUZMA-1989, для уточнения:
1. Для DI каналов подтипов указанных в первой части оставить возможность привязки к пневмоострову?
2. По iolink клапанам это касается только DO модулей или также DI/DO?

**Comment by KUZMA-1989** [comment]
> @KUZMA-1989, для уточнения:
> 1. Для DI каналов подтипов указанных в первой части оставить возможность привязки к пневмоострову?
> 2. По iolink клапанам это касается только DO модулей или также DI/DO?

Di к пневмоострову привязывать нельзя
