### ISSUE TITLE
Блокировка поля адреса в межконтроллерном обмене

### ISSUE THREAD

**Issue by KUZMA-1989** [savushkin-r-d/EasyEPLANner#1366]
При добавлении нового проекта, остается заблокированным поле с адресом
![image](https://github.com/savushkin-r-d/EasyEPLANner/assets/56631906/1c1ba88e-3e0b-4e5d-bc5e-ed17529976eb)

**Comment by KirillGutyrchik** [comment]
@KUZMA-1989, после сохранения и открытия обмена сигналами ошибка исчезает?

**Comment by KUZMA-1989** [comment]
> @KUZMA-1989, после сохранения и открытия обмена сигналами ошибка исчезает?

Вроде, да
