### ISSUE TITLE
Привязка ОС клапанов к дискретным модулям

### ISSUE THREAD

**Issue by SergeiSilakov** [savushkin-r-d/EasyEPLANner#1377]
![image](https://github.com/savushkin-r-d/EasyEPLANner/assets/139815520/c16d4344-de8f-452b-9dda-7c4422ffae71)

**Comment by SergeiSilakov** [comment]
@KirillGutyrchik Для чего выводится эта информация?

**Comment by KirillGutyrchik** [comment]
@SergeiSilakov, #1361.
На схеме эти каналы приявязаны к пневмоострову?

**Comment by SergeiSilakov** [comment]
@KirillGutyrchik Управление да, ОС к DI

**Comment by KirillGutyrchik** [comment]
@SergeiSilakov, поправлю

**Comment by KirillGutyrchik** [comment]
Duplicate #1378.
