### ISSUE TITLE
Некорректная ошибка привязки V_IOLINK_VTUG_DO1_FB_OFF, V_IOLINK_VTUG_DO1_FB_ON, V_IOLINK_VTUG_DO1_DI2

### ISSUE THREAD

**Issue by KUZMA-1989** [savushkin-r-d/EasyEPLANner#1378]
У данных типов **V_IOLINK_VTUG_DO1_FB_OFF, V_IOLINK_VTUG_DO1_FB_ON, V_IOLINK_VTUG_DO1_DI2** `проверяем только DO` `на привязку к каналу IOlLink`, потому что **DI** просто дискретный обычный датчик может быть привязан к любому модулю  
![image](https://github.com/savushkin-r-d/EasyEPLANner/assets/56631906/4ffaca41-c9a1-4ff4-acbd-d46ca3d47e3f)

**Comment by KUZMA-1989** [comment]
@KirillGutyrchik Это обновление не выкладывал еще? А то люди уже ругаются на данные ошибки в проектах

**Comment by KirillGutyrchik** [comment]
> @KirillGutyrchik Это обновление не выкладывал еще? А то люди уже ругаются на данные ошибки в проектах

Выложил, просто в SVN забыл закинуть
