### ISSUE TITLE
Добавить отображение адреса клапанов AS-I 

### ISSUE THREAD

**Issue by KUZMA-1989** [savushkin-r-d/EasyEPLANner#1396]
При нажатии на кнопку "Отображать параметры и свойства" **добавить отображение адреса клапанов AS-I**:

![image](https://github.com/savushkin-r-d/EasyEPLANner/assets/56631906/a8a147e0-1455-4f44-8c58-f794a2be6886)

**Comment by KirillGutyrchik** [comment]
Дублирует #1324.
Уже реализовано в #1325. Но с некоторыми ошибками.

![image](https://github.com/user-attachments/assets/26491a75-99ce-470b-831e-fbcbf23507ff)

**Comment by KirillGutyrchik** [comment]
Duplicate of #1324
