### ISSUE TITLE
Удаление устройств при изменении номера объекта

### ISSUE THREAD

**Issue by SergeiSilakov** [savushkin-r-d/EasyEPLANner#1399]
![image](https://github.com/savushkin-r-d/EasyEPLANner/assets/139815520/c25a71ea-9317-49f4-920d-367a2081c7c3)
При изменении номера объекта епланер удаляет устройства из описания операций с номером объекта на который был изменён.
Например был №1, меняю на №12 - Устройства описанные в операциях с номером ОУ №12(Х12V1) будут удалены.

**Comment by KirillGutyrchik** [comment]
@SergeiSilakov, удалять устройства не должно, вместо этого меняется номер объекта в устройствах на: Q21V1 -> Q11V1. Если такого клапана нет, то да, устройство будет удалено.

**Comment by SergeiSilakov** [comment]
@KirillGutyrchik ну у меня же получилось, у меня есть устройства и они уже были прописаны с ОУ Q21Vx
Их удалило когда я менял номер с 11 на 21 на скрине это видно

**Comment by KirillGutyrchik** [comment]
@SergeiSilakov, ну да, я про это и пишу, когда номер устройства изменяется: 11 -> 21, а до этого были привязаны устройства объекта 21, то вместо того, чтобы оставлять эти устройства как есть, они изменяются на старый номер. То есть, например если в устройсве были прописаны устройства `Q11V1` `Q21V2`, то после изменения номера получится: `Q21V1` `Q11V2` (а так как в данном случае Q11V2 видимо отсутствует на схеме, то оно удаляется из привязки).
Это всегда так работало. Я могу попробовать это поправить, но то, что это не вызовет ошибок в других местах после этого, я гарантировать не могу.
