### ISSUE TITLE
Не посвечиваются седла микспруфов

### ISSUE THREAD

**Issue by KUZMA-1989** [savushkin-r-d/EasyEPLANner#1408]
Когда курсор ставишь на шаг объекта, то не подсвечиваются седла микспруфов
![image](https://github.com/user-attachments/assets/e7f2b731-6d33-44f3-8d18-6cd1e56e2789)

**Comment by KUZMA-1989** [comment]
@KirillGutyrchik Смотри какой есть нюанс при вставке объектов. В танках прописаны выключения микспруфов и их флипование, когда мы вставляем объект эти клапана остаются неизменными и их нужно менять вручную. Обычно у микспруфов в названии воследняя цифра обозначает номер танка (смотри картинку V113, V3 для разных линий - это означает 3-й танк.). Можно ли при вставке, чтоб в микспруфах привязанных менялась последняя цифра, соответствующая номеру объекта?

**Comment by KirillGutyrchik** [comment]
@KUZMA-1989, если у всех микспруфов такая нумерация везде, то да, можно попробовать сделать.

**Comment by KUZMA-1989** [comment]
> @KUZMA-1989, если у всех микспруфов такая нумерация везде, то да, можно попробовать сделать.

Да

**Comment by KirillGutyrchik** [comment]
> > @KUZMA-1989, если у всех микспруфов такая нумерация везде, то да, можно попробовать сделать.
> 
> Да

Тогда можно это в отдельный issue оформить, и подробнее расписать. И для каких подтипов(только микспруфы или еще какие) это применять
