### ISSUE TITLE
Добавить ошибку привязки бачка ледводы к танкам

### ISSUE THREAD

**Issue by KUZMA-1989** [savushkin-r-d/EasyEPLANner#1416]
Если бачок лед воды привязан к аппарату "Танк", то в логах eplaner вывести ошибку о неправильности привязки бачка ледводы

**Comment by KirillGutyrchik** [comment]
@KUZMA-1989, к какому базовому объекту он относится? Я что-то не нахожу.

**Comment by KUZMA-1989** [comment]
> @KUZMA-1989, к какому базовому объекту он относится? Я что-то не нахожу.

Бачок откачки лелводы

**Comment by KirillGutyrchik** [comment]
> Бачок откачки лёдводы

Все, я нашел. Подумал, что он отмечен как устаревший. Только для него ошибку добавлять?

**Comment by KUZMA-1989** [comment]
> > Бачок откачки лёдводы
> 
> Все, я нашел. Подумал, что он отмечен как устаревший. Только для него ошибку добавлять?
Да

**Comment by KUZMA-1989** [comment]
> > > Бачок откачки лёдводы
> > 
> > 
> > Все, я нашел. Подумал, что он отмечен как устаревший. Только для него ошибку добавлять?
> > Да

еще "Бойлер" добавь
