### ISSUE TITLE
Ограничения внутри объекта

### ISSUE THREAD

**Issue by KUZMA-1989** [savushkin-r-d/EasyEPLANner#143]
Сделать, чтоб в ограничениях внутри объекта не отображалась операция, для для которой ты сейчас расставляешь ограничения.

**Comment by dimabeel** [comment]
@KUZMA-1989 , может быть номер объекта?

**Comment by KUZMA-1989** [comment]
@dimabeel Когда в eplan в "ограничениях внутри объекта" ты расставляешь ограничения, там отображается и та операция, для которой ты выставляешь ограничения и можно по ошибке поставить, что при мойке например нельзя включить мойку. Надо чтоб та операция в объекте, для которой ты расставляешь не отображалась в списке операций

**Comment by dimabeel** [comment]
@KUZMA-1989 , все, дошло. Я понял :)
