### ISSUE TITLE
Ограничения внутри объектов одинакового типа

### ISSUE THREAD

**Issue by KUZMA-1989** [savushkin-r-d/EasyEPLANner#144]
Сделать, чтоб в ограничениях внутри объекта с одинаковым типом была синхронизация. Если изменяешь в одном объекте, то в о всех также изменялись ограничения

**Comment by dimabeel** [comment]
@KUZMA-1989 , представим ситуацию, когда объект с одинаковым типом, а ограничения должны быть разными. Что делать в таком случае? Система их обновит и ты не сможешь настроить ограничения т.к она постоянно будет их синхронизировать. Или такая ситуация невозможна?

**Comment by KUZMA-1989** [comment]
Один тип он и есть один тип, все одинаково

**Comment by dimabeel** [comment]
@KUZMA-1989 , хорошо, я понял

**Comment by dimabeel** [comment]
@KUZMA-1989 , смотрю проект для примера. Там четыре объекта одинакового типа. Но у них отличаются ограничения. Почему? Это противоречит этому запросу.

Объект 1:
![image](https://user-images.githubusercontent.com/32632640/75147859-59be6f80-570f-11ea-8ac4-3995de5c9f90.png)


Объект 2:
![image](https://user-images.githubusercontent.com/32632640/75147845-51663480-570f-11ea-9bfa-679f7c83f123.png)

Объект 3:
![image](https://user-images.githubusercontent.com/32632640/75147895-6e026c80-570f-11ea-8974-89c8d9bd3213.png)

Объект 4:
![image](https://user-images.githubusercontent.com/32632640/75147818-40b5be80-570f-11ea-9a30-e2e4f3214723.png)

Тип один и тот же. Почему отличаются ограничения? В частности, последние 3 ограничения на каждом из объектов.

**Comment by KUZMA-1989** [comment]
@dimabeel  ограничения внутри объекта поле, там все одинаково 5,2 6,2 7,2 8,2, первый номер это номер объекта, а вторая цифра это операция

**Comment by KUZMA-1989** [comment]
Нас интересуют именно "Ограничения внутри объекта"

**Comment by dimabeel** [comment]
Я понял

**Comment by dimabeel** [comment]
@KUZMA-1989 , а ограничение "На последующие операции" используется? Третий тип ограничений, в самом низу списка ограничений.

**Comment by KUZMA-1989** [comment]
@dimabeel Если они относятся к операциям только данного объекта, то да
