### ISSUE TITLE
Функциональность обновления базы каналов для старых проектов (ICP CON -> PXC PLCNext)

### ISSUE THREAD

**Issue by idzm** [savushkin-r-d/EasyEPLANner#1441]
Необходима функциональность обновления базы каналов для старых проектов (**ICP CON** -> **PXC PLCNext**). Она заключается в следующем: **ID** канала не изменяется, изменяется текст по следующему правилу:
`LE320 : 32LE уровень танка №32`  -> `T32LT1.V : Уровень танка №32`
`LS101 : Нижний уровень бачка ледяной воды` - > `LS101.ST : Нижний уровень бачка ледяной воды`
`V3201 : 32V1 Донный танка №32` -> `T32V1.ST : Донный танка №32`, `T32V1.M : Донный танка №32`

Предлагается следующий алгоритм:
1. Генерируем базу каналов;
2. Открываем соответствующую старую базу каналов;
3. Для каждого элемента (тег) старой базы каналов ищем элемент (тег) новой базы каналов, далее для него меняем его `ID` на `ID` из старой базы каналов.

**Comment by VadimZezyotkoATP** [comment]
[BR1-Танки-32-34.txt](https://github.com/user-attachments/files/17461572/BR1-.-32-34.txt)
