### ISSUE TITLE
IFM.PM1706 Датчик давления и уровня (PT и LT)

### ISSUE THREAD

**Issue by painterlv** [savushkin-r-d/EasyEPLANner#1459]
Добавить в список поддерживаемых изделий с областями ввода-вывода устройство IFM.PM1706
Диапазон измерения -0.125...2.5 bar

**Comment by painterlv** [comment]
Привет! Запросы выполнены и приняты, теперь нужно дождаться релиза сборки епланера на это обновление?

**Comment by KirillGutyrchik** [comment]
> Привет! Запросы выполнены и приняты, теперь нужно дождаться релиза сборки епланера на это обновление?

Привет. Да, сейчас выложу обновлениею.
