### ISSUE TITLE
Сброс параметров и номера следующего шага в объектах при копировании параметров

### ISSUE THREAD

**Issue by KUZMA-1989** [savushkin-r-d/EasyEPLANner#1482]
Сбрасываются привязанные параметры и номера следующего шага в объектах при копировании параметров из одного объекта в другой (копировал из танка в танк)
![image](https://github.com/user-attachments/assets/9b2442c5-0917-4a3f-b40a-06d5dce9502d)

**Comment by KirillGutyrchik** [comment]
@KUZMA-1989, это изначально так и задумано, что ривязка параметров будет сбрасываться, если их заменять. Могу предложить 2 варинта:
 - Если lua-имя заменненого параметра совпадает, то его привязку не сбрасывать;
 - Вывод диалогового окна с выбором сбрасывать/не сбрасывать привязку;

**Comment by KUZMA-1989** [comment]
> @KUZMA-1989, это изначально так и задумано, что привязка параметров будет сбрасываться, если их заменять. Могу предложить 2 варинта:
>  - Если lua-имя заменненого параметра совпадает, то его привязку не сбрасывать;
>  - Вывод диалогового окна с выбором сбрасывать/не сбрасывать привязку;

Первый вариант
