### ISSUE TITLE
Добавить артикул блоков питания IOLink

### ISSUE THREAD

**Issue by KUZMA-1989** [savushkin-r-d/EasyEPLANner#1493]
Размерность IOLink Вход **144** Вход **56**
![image](https://github.com/user-attachments/assets/282e8d29-902e-4a90-b8f0-559fa7407e69)

![image](https://github.com/user-attachments/assets/d43b12a8-2eab-4f73-b183-99f007f4fe01)

**Comment by KirillGutyrchik** [comment]
Duplicate #1487.
Implemented #1489.
