### ISSUE TITLE
Запись статистики о проекте

### ISSUE THREAD

**Issue by idzm** [savushkin-r-d/EasyEPLANner#150]
В целях упрощения визуального представления статистической информации о проекте, необходимо при закрытии проекта также сохранять следующее:
Первая итерация:
- [x] количество строк в модуле `main.plua` записать в файл `lines_total.svg`;
- [x] количество тегов проекта - `tags_total.svg`;
- [x] количество аппаратов проекта (*[units](https://github.com/savushkin-r-d/EasyEPLANner/tree/master/docs/user_manual#91-Объектная-модель-рецептурного-производства )*) - `units_total.svg`;
- [x] количество агрегатов проекта (*[equipment modules](https://github.com/savushkin-r-d/EasyEPLANner/tree/master/docs/user_manual#91-Объектная-модель-рецептурного-производства )*) - `agregates_total.svg`.

Upd (by @dimabeel)
Вторая итерация:
- [x] Динамически высчитывать процентное соотношение на основе констант, что бы полоса состояния (зеленого цвета) была не статическая.

Константы:
1. Количество строк кода - 1000 строк.
2. Количество юнитов - 10 штук.
3. Количество агрегатов - 50 штук.
4. Количество тэгов - 5000 штук.

Файлы размещать в каталоге проекта в `docs\statistics`.

Статистику сохранять в виде `svg` файлов. Образец (для генерации соответствующих картинок):
```xml
<?xml version="1.0" encoding="UTF-8"?>
<svg width="100" height="20" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">

  <rect rx="4" x="0" width="100" height="20" fill="dimgrey"/>
  <rect rx="4" x="0" width="90.0" height="20" fill="green"/>

  <g fill="#fff" text-anchor="middle" font-family="DejaVu Sans,Verdana,Geneva,sans-serif" font-size="11">
    <text x="50.0" y="14">
        30 агрегат(ов)
    </text>
  </g>
</svg>
```
Вот как будет выглядеть картинка: ![agregates_total](https://user-images.githubusercontent.com/23375200/75224448-8f1f9780-57b9-11ea-9d52-2d0cdc1abf45.png)

**Comment by dimabeel** [comment]
@idzm , шаблон битый. Не работает с буквами. С цифрами работает отлично.
