### ISSUE TITLE
Реализовать описание аппарата

### ISSUE THREAD

**Issue by idzm** [savushkin-r-d/EasyEPLANner#154]
Для аппарата (это в основном танки) реализовать следующие ниже элементы описания.
- [x] оборудование: 
```lua
prg.tank1.hatch		= prg.control_modules.TANK1GS1 --Датчик люка.
prg.tank1.LS_up		= prg.control_modules.TANK1LS2 --Датчик верхнего уровня.
prg.tank1.LS_down	= prg.control_modules.TANK1LS1 --Датчик нижнего уровня.
prg.tank1.LT		= prg.control_modules.TANK1LT1 --Датчик текущего уровня.
prg.tank1.temperature	= prg.control_modules.TANK1TE1 --Датчик температуры.
```
- [x] операция наполнения:
```lua
prg.tank1.operations.FILL = 2					--Номер операции наполнения.
prg.tank1.OPERATION_AFTER_FILL = prg.tank1.operations.STORING	--Операция после наполнения.
```

- [x] операция хранения:
```lua
prg.tank1.operations.STORING = 3
```

- [x] операция выдачи:
```lua
prg.tank1.operations.OUT = 4
```

- [x] параметры, сбрасываемые после начала мойки:
```lua
prg.tank1.reset_before_wash =
    {
    prg.tank1.PAR_FLOAT.V_ACCEPTING_CURRENT,
    prg.tank1.PAR_FLOAT.PRODUCT_TYPE,
    prg.tank1.PAR_FLOAT.V_ACCEPTING_SET
    }
```

- [x] мастер проекта:
```lua
prg.tank1.master = prg.master1
```

**UPD**
- [x] модификация доп. сигналов моек:
```lua
prg.tank10.DI_CIP_FREE = prg.control_modules.MCA2LINE2DI1
 ```

- [x] Сделать, что бы можно выбрать только 1 конкретную базовую операцию на объект (две одинаковые базовые операции на объект недопустимы).

- [x] Рефакторинг полученного кода.

- [x] Документировать эти изменения в пользовательской документации

**Comment by dimabeel** [comment]
@idzm 
> self.OPERATION_AFTER_FILL = self.operations.STORING	--Операция после набора.

Каким образом задавать это?

**Comment by dimabeel** [comment]
- [ ] модификация доп. сигналов моек:
```lua
prg.tank10.DI_CIP_FREE = prg.control_modules.MCA2LINE2DI1
```

**Comment by dimabeel** [comment]
Также:

- [ ] Сделать, что бы можно выбрать только 1 конкретную базовую операцию на объект
