### ISSUE TITLE
Доработка привязки устройств для поля оборудование

### ISSUE THREAD

**Issue by KUZMA-1989** [savushkin-r-d/EasyEPLANner#176]
- [x] ~Сделать привязку устройств в поле оборудование по клику на устройство.~ Уже есть.
- [x] Сделать возможность копирования этого поля в другой такой объект, как всех устройств сразу,так и по отдельному полю (аналогично как копируются параметры). 
- [x] Можно ли сделать, чтобы данные поля заполнялись автоматически: имя объекта есть, список устройств тоже есть - что мешает это сделать?

**Comment by dimabeel** [comment]
1. Привязка устройств в поле оборудование по клику на устройство уже была добавлена ранее и корректно работает (протестировано 09.03.2020 повторно).
2. Будет добавлено.
3. Ответ на текущий день - в данный момент нет возможности идентифицировать определенное устройство, кроме как по тексту в поле "Примечание", а ошибки ввода в этом поле (и необходимость всегда вводить в это поле определенные строгие значения) приведут к некорректному срабатыванию автоматического заполнения при условии некорректного/отсутствующего примечания у устройства. Но будет рассмотрено глубже, потому что, действительно, ОУ у нас есть, номер устройства есть. Остается лишь определиться, как определять то или иное устройство.
