### ISSUE TITLE
Для датчика текущего уровня LT добавить задание аварийного значения

### ISSUE THREAD

**Issue by idzm** [savushkin-r-d/EasyEPLANner#181]
Добавить параметр `P_CLEVEL_ERR` - это значение будет передаваться в случае аварии (датчики либо модуля).

**Comment by dimabeel** [comment]
@idzm , предлагаю `P_ERR` т.к это будет удобнее с точки зрения пользователя

**Comment by idzm** [comment]
Ок, параметр будет называться `P_ERR`.
