### ISSUE TITLE
Добавить для линии наполнения базовую операцию "Наполнение"

### ISSUE THREAD

**Issue by idzm** [savushkin-r-d/EasyEPLANner#228]
Вот пример сохранения:
```lua
prg.line_c2.operations =         --Операции.
    {
    WASHING_CIP = 1,        --Мойка CIP.
    FILL = 2,               --Наполнение.
    }
```
Также добавить шаги:
```lua
prg.line_c2.steps =         --Шаги операций.
    {
    WASHING_CIP =
        {
        DRAINAGE = 2,
        },
    FILL =
        {
        WAITING_KEY = 1,
        IN_DRAINAGE = 2,
        IN_TANK     = 3,
        }
    }
```
 Шаги можно редактировать, если записано -1, то тогда данный шаг не записывать:
```lua
prg.line_c2.steps =         --Шаги операций.
    {
    WASHING_CIP =
        {
        DRAINAGE = 2,
        },
    FILL =
        {
        IN_DRAINAGE = 2,
        IN_TANK     = 3,
        }
    }
```
Шаг в танк всегда обязательный (не может отсутствовать):
```lua
prg.line_c2.steps =         --Шаги операций.
    {
    WASHING_CIP =
        {
        DRAINAGE = 2,
        },
    FILL =
        {
        IN_TANK = 3,
        }
    }
```

**Comment by dimabeel** [comment]
Прогресс:
- [ ] Переименованы файлы с папками в имитации базы данных.
- [ ] Перенесены методы имитации в более логичное расположение.
- [ ] Базовая реализация базовых шагов.
- [ ] Сохранение базовых шагов в main.objects
- [ ] Чтение базовых шагов из main.objects
- [ ] Сброс базовых шагов при изменении объектов или их операций (базовых)
- [ ] Сохранение в prg.lua согласно заданию
