### ISSUE TITLE
Добавить новый базовый объект "Узел давления ПИД"

### ISSUE THREAD

**Issue by idzm** [savushkin-r-d/EasyEPLANner#237]
В файл prg.lua добавить необходимый модуль:
```lua require( "pressure" ) ```

Базовое описание следующее:
```lua
add_functionality(prg.pressure_node_PID_c1, basic_pressure_node_PID)
```
Добавляется одна базовая операция - работа. Образец сохранения описания:
```lua
prg.pressure_node_PID_c1.operations =
    {
    WORKING = 1,
    }
```
Оборудование - датчик давления и мотор:
```lua
prg.pressure_node_PID_c1.PT = prg.control_modules.C1PT1
prg.pressure_node_PID_c1.M1 = prg.control_modules.C1M1
```

**Comment by dimabeel** [comment]
Добавить ещё его привязку через "Привязанные устройства"
