### ISSUE TITLE
Доработка базовых агрегатов с ПИД-регулированием

### ISSUE THREAD

**Issue by idzm** [savushkin-r-d/EasyEPLANner#270]
Для всех текущих  базовых агрегатов с ПИД-регулированием добавляется дополнительное оборудование (*AI1/номер параметра*) для указания задания ПИД-регулятора:
```lua
prg.flow_node_pid_o2.SET_VALUE_PAR_NUMBER_OR_AI1 = 2
--или 
prg.flow_node_pid_o2.SET_VALUE_PAR_NUMBER_OR_AI1 = prg.control_modules.O2AI1
```
Оно не может быть пустым.

**Comment by KUZMA-1989** [comment]
@idzm А то, что я писал сделать для ПИД вход и задание поля универсальные не подходит?

**Comment by idzm** [comment]
Это и есть - здесь я конкретно название указал и как в Eplanner будет называться.

**Comment by idzm** [comment]
Также предлагается вместо номера параметра использовать Lua-имя:
```lua
prg.flow_node_pid_o2.SET_VALUE_PAR_NUMBER_OR_AI1 = prg.flow_node_pid_o2.PAR_FLOAT.HEAT_TEMPERATURE
```
