### ISSUE TITLE
Полное описание базовых агрегатов - узлов охлаждения, нагрева, ...

### ISSUE THREAD

**Issue by idzm** [savushkin-r-d/EasyEPLANner#279]
- [x] Дополнительно для аппаратов при использовании бачка лёдводы (обычного и ПИД) должно сохраняться описание в следующем виде:
```lua
prg.cream_tank1.ice_water_pump_tank = prg.cw_tank1
```
- [x] Также шаги бачка лёдводы должны быть описаны так:
```lua
prg.cw_tank1.steps =         --Шаги операций.
    {
    COOLING =
        {
        WAITING_HI_LS  = 1,
        WAITING_LOW_LS = 2,
        }
    }
```
- [x] Операции и шаги для узла нагрева:
```lua
--...
HEATING = 1,
--...
HEATING =
    {
    WORKING = 1,
    WAITING = 2,
    },
```
- [x] Шаги для узла охлаждения (обычного и ПИД):
```lua
--...
COOLING =
    {
    WORKING = 1,
    WAITING = 2,
    },
```
- [x] Для описания обычного бачка лёдводы и бачка лёдводы ПИД использовать следующие Lua-имена:
```basic_ice_water_pump_tank``` и ```basic_ice_water_pump_tank_PID```.

**Comment by dimabeel** [comment]
@idzm , почему это bug?

**Comment by dimabeel** [comment]
@idzm , что значат эти цифры?

> ```lua
>         WAITING_HI_LS  = 1,
>         WAITING_LOW_LS = 2,
> ```

Номера шагов?

**Comment by idzm** [comment]
Да. Получается, prg.lua переписывает операции и шаги базовых агрегатов.  Можно, как вариант, для них убрать описание шагов и операций из prg.lua. Как такой вариант?

**Comment by dimabeel** [comment]
Документацию забыл
