### ISSUE TITLE
Добавить механизм версий

### ISSUE THREAD

**Issue by dimabeel** [savushkin-r-d/EasyEPLANner#28]
**Ваш запрос связан с проблемой? Пожалуйста, опишите.**
Нет возможности узнать версию системы.

**Опишите решение, которое Вы хотели бы**
Добавить механизм версий для надстройки, что бы лучше ориентироваться в ней при возникновении каких либо ошибок, или при внесении доработок.

**Опишите альтернативы, которые Вы рассматривали**
Других альтернатив в надстройке нет.

**Дополнительная информация**
Надо проработать систему версий, её нумерацию и порядок.

**Comment by dimabeel** [comment]
@idzm, есть предложения по нумерации и порядку этой нумерации? Не учитывая имеющуюся по типу *год.месяц*. Если в месяце несколько версий выпущено, то надо что-то ещё. Например, *год.месяц.день*. А если за 1 день несколько багфиксов, то предусмотреть *год.месяц.день.порядковый_номер_за_день*?

**Comment by dimabeel** [comment]
Данное предложение  принято при обсуждении с @idzm.
> год.месяц.день.порядковый_номер_за_день

**Comment by idzm** [comment]
Может такой вариант:  `год.месяц.день.глобальный_порядковый_номер_сборки`?

**Comment by dimabeel** [comment]
Принят вариант: `год.месяц.сборка.ревизия`. В итоге можно получить, например: _2019.13.7303.15000_.

Поля **Сборка** и **Ревизия** вычисляются системой автоматически.

**Сборка** - день, отсчитываемый с 1 _января_ 2000 года. 
**Ревизия** - время в секундах, отсчитываемое с полуночи текущего дня.

**Comment by idzm** [comment]
Согласен, принято.
