### ISSUE TITLE
Автоматическое включение мойки по сигналам 

### ISSUE THREAD

**Issue by KUZMA-1989** [savushkin-r-d/EasyEPLANner#281]
Сделать поле "Автоматическое включение мойки", чтобы прописывать туда сигналы.

Логика следующая: 

- Если в поле "Автоматическое включение мойки" есть сигнал, а в поле "Завершение мойки" нет сигнала, то мойка включается по сигналу из поля "Автоматическое включение мойки" и выключается по его пропаданию.

- Если в поле "Автоматическое включение мойки" есть сигнал и в поле "Завершение мойки" есть сигнал, то мойка включается по сигналу из поля "Автоматическое включение мойки", а по сигналу из поля "Завершение мойки" либо выключается, либо переходит в шаг дренаж, если таковой имеется.

**Comment by dimabeel** [comment]
@KUZMA-1989 с логикой к @idzm. Куда нужно добавить это поле? В какие объекты? В какие операции?

**Comment by KUZMA-1989** [comment]
@dimabeel Для всех объектов

**Comment by dimabeel** [comment]
@KUZMA-1989 , то есть, по этому сигналу будет включаться мойка какого-то конкретного объекта, верно?

**Comment by KUZMA-1989** [comment]
@dimabeel Да, это поле в объекте, можно добавить рядом с полем мойка завершена

**Comment by dimabeel** [comment]
@KUZMA-1989 , мойка завершена - это сигнал в операции "Мойка" для объектов, это не сигнал конкретного объекта. Я думаю, что этот сигнал стоит добавить в операцию "Мойка"

**Comment by KUZMA-1989** [comment]
Да, именно так, у меня eplan не открыт просто

**Comment by dimabeel** [comment]
@KUZMA-1989 , хорошо. Я понял

**Comment by idzm** [comment]
Сигнал "Автоматическое включение мойки" для сохранения описания будет называться ```CIP_WASH_REQUEST```.
