### ISSUE TITLE
Разработать тест по документации для инженеров по автоматизации

### ISSUE THREAD

**Issue by idzm** [savushkin-r-d/EasyEPLANner#288]
В целях проверки знаний инженеров по автоматизации, использующих **Eplanner**, разработать тесты по текущей пользовательской документации.
Тесты разработать в *.md формате в виде вопросов по разделам документации. Вопросы должны иметь пять вариантов ответа (возможно несколько правильных). Документ с вопросами поместить в https://github.com/savushkin-r-d/EasyEPLANner/tree/master/docs/user_manual/test/ReadMe.md.

**Comment by AS005016** [comment]
Хорошо, задание поняла. А сколько вопросов должно быть для каждого раздела?

**Comment by idzm** [comment]
Для первой версии исходя из объема раздела: страница текста - 2 вопроса.

**Comment by AS005016** [comment]
Хорошо.
