### ISSUE TITLE
Привязка дискретных устройств к модулям IO-Link

### ISSUE THREAD

**Issue by KUZMA-1989** [savushkin-r-d/EasyEPLANner#30]
Все дискретные устройства должны иметь возможность привязываться к IO-Link каналам.

**Comment by dimabeel** [comment]
@KUZMA-1989 , по принципу 1 устройство - 1 канал (DI или DO) IO-Link?

**Comment by dimabeel** [comment]
@KUZMA-1989 , сигналы DI,DO учитывать (которые вне устройств)? Устройства - дискретный выход, вход

**Comment by KUZMA-1989** [comment]
Да,любое устройство или дискретный сигнал DI-DO можно подключить к каналу IO-Link

**Comment by dimabeel** [comment]
@KUZMA-1989 , предполагается, что устройство имеет только 1 сигнал DI или DO? Или же возможно наличие и других сигналов (AI,AO, а так же смесь аналоговых и дискретных сигналов)

**Comment by KUZMA-1989** [comment]
У модуля IO-Link канал настроить можно дополнительно на DO или DI, AI и AO нету

**Comment by dimabeel** [comment]
@KUZMA-1989 , я про привязываемые устройства. Привязываемое устройство какой набор каналов может иметь?

**Comment by KUZMA-1989** [comment]
![image](https://user-images.githubusercontent.com/56631906/71612758-804ea700-2bb3-11ea-82a6-c8a4db23e279.png)

**Comment by KUZMA-1989** [comment]
@dimabeel ТЫ про это?

**Comment by dimabeel** [comment]
@KUZMA-1989 , нет. Количество каналов (сигналов) на устройство и их типы. Например, двигатель M может иметь канал AO и канал DI. Такие комбинации предполагают же, что DI привяжется на IO-Link, а AO в другое место?

**Comment by KUZMA-1989** [comment]
Да
