### ISSUE TITLE
Выбор тип канала на модулях IO-Link

### ISSUE THREAD

**Issue by KUZMA-1989** [savushkin-r-d/EasyEPLANner#31]
Для того, чтобы исключить ошибку привязки, для каждого канала добавляется выбор типа: 
* DI; 
* DO; 
* IO-Link;
* отключен.

**Comment by dimabeel** [comment]
@KUZMA-1989 , что должен делать тип "Отключен"? Он чисто графически отображается? Или будет привязано устройство, но отключено?

**Comment by dimabeel** [comment]
@KUZMA-1989 , 

> для каждого канала добавляется выбор типа:

Для каждого канала **IO-Link** модуля?

**Comment by KUZMA-1989** [comment]
Честно я не знаю как это реализовать, это @idzm захотел

**Comment by dimabeel** [comment]
@KUZMA-1989 , Ок. Буду работать

**Comment by dimabeel** [comment]
@idzm, реализация типа канала без типа "Отключен" пойдет? Я не вижу никакой смысловой нагрузки, потому что если к каналу ничего не привязано, то в проектах много где пишут "Резерв", что бы использовать канал как резервный в будущем, или ничего не пишут.

А если к каналу что-то привязано, то оно в работе.

@KUZMA-1989 , я все верно описал?

**Comment by idzm** [comment]
Ок, может быть и так.
