### ISSUE TITLE
Ошибки устройств IO-Link

### ISSUE THREAD

**Issue by KUZMA-1989** [savushkin-r-d/EasyEPLANner#332]
Для всех измерительных приборов нужно ,чтоб была возможность для изменения значения ошибки P_ERR, сейчас для давления нету например, это важно когда используется датчик в регулировании!

**Comment by dimabeel** [comment]
@idzm, P_ERR добавлять в конец списка параметров? Будет добавлено для всех IO-Link устройств, не только для PT.

**Comment by idzm** [comment]
С учетом роста количества параметров у устройств, надо сделать их инициализацию по имени вместо индекса.

**Comment by idzm** [comment]
Предлагается вначале реализовать значения ошибки **P_ERR** для всех устройств, а после отдельно реализовать работу с параметрами устройств по имени.
