### ISSUE TITLE
Добавить подтипы устройств - виртуальный текущий и дискретный уровни.

### ISSUE THREAD

**Issue by rartem** [savushkin-r-d/EasyEPLANner#34]
//LS
            DST_LS_MIN = 1,     ///< Подключение по схеме минимум.
            DST_LS_MAX,         ///< Подключение по схеме максимум.

            LS_IOLINK_MIN,      ///< IOLInk уровень. Подключение по схеме минимум.
            LS_IOLINK_MAX,      ///< IOLInk уровень. Подключение по схеме максимум.

            **DST_LS_VIRT,**        ///< Виртуальный датчик уровня.

           //LT
            DST_LT = 1,    ///Текущий уровень без дополнительных параметров.
            DST_LT_CYL,    ///Текущий уровень для цилиндрического танка.
            DST_LT_CONE,   ///Текущий уровень для танка с конусом в основании.
            DST_LT_TRUNC,  ///Текущий уровень для танка с усеченным цилиндром в основании.

            DST_LT_IOLINK, ///Текущий IOLInk уровень без дополнительных параметров.

            **DST_LT_VIRT**,   ///< Виртуальный текущий уровень.

**Comment by dimabeel** [comment]
Доделать документацию
