### ISSUE TITLE
Добавление базовых аппаратов через Lua-описание

### ISSUE THREAD

**Issue by idzm** [savushkin-r-d/EasyEPLANner#355]
Так как сейчас активно добавляются базовые аппараты, необходимо разработать механизм их описания в виде Lua-скрипта с дальнейшим считыванием. Тогда не придётся модифицировать дополнение при добавлении\изменении аппаратов.

**Comment by dimabeel** [comment]
@idzm, почему мы не можем объединить вместе с #353?

**Comment by idzm** [comment]
Трудоемкие вещи - можно разделить.

**Comment by dimabeel** [comment]
Ладно, позже. Надо сразу другое сделать. Нужно будет скорее всего перерабатывать всё.

**Comment by idzm** [comment]
Ок.
