### ISSUE TITLE
Для базового агрегата "Узел давления" добавить сигнал запроса продукта

### ISSUE THREAD

**Issue by idzm** [savushkin-r-d/EasyEPLANner#368]
Если необходимо, узел давления может работать только при активном сигнале запроса продукта от приёмника. Данный параметр называется `product_request` и привязывается к дискретному входу (`DI`).

**Comment by dimabeel** [comment]
@idzm , это по сигналу в операции "Работа"?

**Comment by idzm** [comment]
Да.

**Comment by dimabeel** [comment]
Будет добавлено после того как #362 будет слит. Что бы не дублировать работу по двадцать раз

**Comment by idzm** [comment]
Ок.

**Comment by dimabeel** [comment]
В новом функционале для решения этой проблемы нужно будет добавить этот код для параметров операции работа. Будет добавлен активный параметр "Запрос продукта".
```LUA
active =
{
    product_request = { name = "Запрос продукта" },
}
```
