### ISSUE TITLE
Оптимальное сохранение параметров

### ISSUE THREAD

**Issue by idzm** [savushkin-r-d/EasyEPLANner#373]
Предлагается при сохранении описания (в **prg.lua**, **main.objects.lua**) для полей, у которых нет значения (значение **nil**), опускать их запись. Это позволить более оптимально (наглядно) получить описание - если поле не задано, значит его и нет в описании.

**Comment by dimabeel** [comment]
Хорошо, сделаю после того, как разберусь с экспортом/импортом

**Comment by dimabeel** [comment]
@idzm , для steps, operations в prg.lua делаем аналогично? Пустую таблицу можно убрать, или лучше все же оставить?

**Comment by dimabeel** [comment]
Если параметр не сохраняется, и в этой таблице параметров больше нет, то пустую таблицу я тоже не пишу, например:

До:

prg.tank1.FILL =
```LUA
{
OPERATION_AFTER_FILL = nil,
}
```

После: этот код написан не будет.

**Comment by idzm** [comment]
Да - пустые таблицы тоже не пишем.
