### ISSUE TITLE
Доработка описания базовой операции "Мойка"

### ISSUE THREAD

**Issue by idzm** [savushkin-r-d/EasyEPLANner#386]
Необходимо добавить следующие элементы описания:
```lua
    MEDIUM_CHANGE_REQUEST =
    steps.WASHING_CIP.MEDIUM_CHANGE = 
    out_pump =
```
`MEDIUM_CHANGE_REQUEST` - сигнал запроса смены среды. Приходит с CIP-станции.
`MEDIUM_CHANGE` - шаг смены среды - в нем объект откачивается до опорожнения (до НУ).
`out_pump` -  откачивающий насос. В зависимости от настроек (параметр) может работать непрерывно, либо только при активном НУ.

**Comment by dimabeel** [comment]
@idzm, для какого базового объекта?

**Comment by idzm** [comment]
Это делаем для танка. `out_pump` - да, только на насос.

**Comment by dimabeel** [comment]
@idzm , какое устройство стандартное для откачивающего насоса? M1?

**Comment by idzm** [comment]
Да.
