### ISSUE TITLE
Типовое описание устройств, получаемых через Modbus TCP

### ISSUE THREAD

**Issue by idzm** [savushkin-r-d/EasyEPLANner#391]
Необходимо, чтобы описание устройств, состояние которых получается через Modbus TCP (от шлюзов, других контроллеров и т.п.), присутствовало в проекте. В настоящее время достаточно много таких устройств и обработка их вручную (ручная правка файлов описания) уже не эффективна.
@KUZMA-1989 готов поучаствовать в тестовом использовании описания.

**Comment by dimabeel** [comment]
@idzm что за файлы? что за устройства?

**Comment by idzm** [comment]
@rartem поможет, у него уже есть идеи по реализации.

**Comment by dimabeel** [comment]
@idzm это после перевода на 2.9 или до?

**Comment by idzm** [comment]
Давай после уже.
