### ISSUE TITLE
Указание операции перемешивания для узла при наличии более 1-ой таковой

### ISSUE THREAD

**Issue by idzm** [savushkin-r-d/EasyEPLANner#400]
При наличии реверса у узла перемешивания появляются две операции: перемешивание влево и перемешивания вправо (мотор мешалки работает в реверсе).
Во всех операциях должен работать узел перемешивания: в операциях мойка, наполнение и перемешивания - влево, в операциях внесения закваски, отделение сыворотки, хранение, выдача - вправо. У инженеров по автоматизации должна быть возможность это указывать (и изменять при необходимости).

**Comment by dimabeel** [comment]
Посмотрев #401, есть несколько путей развития:
1. Я могу добавить просто привязочные параметры в каждую операцию при привязке узла перемешивания (параметр - номер операции перемешивания в узле перемешивания). Это самый простой способ, он требует только введения обработки такого типа параметра в операции "Мойка";
2. Подумать над переработкой параметров. Появятся отдельные параметры операций, отдельные параметры оборудования (разные классы). Параметры операций также будут разделены на те, в которых указываются: устройства и параметры, номера операций, прочие данные, булевые значения (пока что четыре типа, может будет больше).
3. По принципу первого параметра, только ещё будет дописан метод обработки обработки номеров введенных операций, что бы операция записывалась в prg.lua её адресом (Prg.mix.operations.mixing), а не цифрой.

@idzm , что скажешь?

**Comment by dimabeel** [comment]
Я хочу попробовать оставить параметры в нынешнем положении, но ввести тригеры введенных значений: isBool (уже есть), isDevice (ещё нет), isParameter (ещё нет), isNumber (ещё нет). В итоге можно будет обработать в зависимости от введенного значения параметр. Если булевское (для булевского параметра, он остается классом) - одно сохранение, если введено устройство - другое и т.д. В перспективе мы можем легко расширять это поведение т.к у нас всегда одно сохранение:

1. Для устройства - prg.control_modules.DEVICE
2. Для параметра - object.PAR_FLOA.PARAMETER
3. Для числа - сейчас числами мы указываем только номера операций (если будет что-то ещё, то придется переделывать по другому, или такой вариант всегда будет?)
4. Для булевского - true/false

**Comment by idzm** [comment]
Пойдет - с типами и проверки введенных значений проще реализовывать.

**Comment by dimabeel** [comment]
@idzm , что если, перемешивание в операции не должно выполняться. Что тогда?

**Comment by idzm** [comment]
Надо добавить параметр - использовать перемешивание во время операции.

**Comment by idzm** [comment]
Если перемешивание не нужно, то дальше можно по разному: или не отображать, или 0 писать.

**Comment by dimabeel** [comment]
> Если перемешивание не нужно, то дальше можно по разному: или не отображать, или 0 писать.

Это слишком уникальный случай на текущий момент. Нужно думать, что делать. Тут быстрыми решениями точно не отделаться

**Comment by dimabeel** [comment]
Также, приведение к одному типу сохранения привело к тому, что мы должны отказываться от задания параметров непосредственно в самом объекте:

```LUA
prg.OBJECT1.CIP_FREE = <value>
```

должно перейти в:

```LUA
prg.OBJECT1.WASHING_CIP = {
     CIP_FREE = <value>
}
```

Это коснется всех параметров операции "Мойка", которые реализованы на текущий момент:

```
CIP_WASH_REQUEST
CIP_WASH_END
DI_CIP_FREE
MEDIUM_CHANGE_REQUEST
```

**Comment by idzm** [comment]
Пойдет. Только упрощаем:
```LUA
prg.OBJECT1.WASH = 
    {
    CIP_FREE = <value>
    }
```

**Comment by dimabeel** [comment]
А что будет с файлами main.plua? Там же используется prg.OBJECT1.CIP_WASH

**Comment by idzm** [comment]
Да.

**Comment by dimabeel** [comment]
В данный момент реализовано всё, что запрошено в issue, но нужно подумать по поводу того, что бы отключить/удалить/сделать неактивными/обнулить параметры, которые добавляются агрегатами если в операции они не будут использоваться. Поэтому, если нужный issue нужен сейчас, то я предлагаю вынести это в отдельный запрос. А если не срочно - то тут надо работать дальше (включая тестирование, документацию)

**Comment by idzm** [comment]
Пока можно оставить параметры как есть - в неиспользуемые пусть 0 пишется.

**Comment by dimabeel** [comment]
> Пока можно оставить параметры как есть - в неиспользуемые пусть 0 пишется.

Это тоже пока не реализуемо. Нужно следить за конкретным параметром. Любое изменение параметра использования узла "Да/Нет" никак не отследить на данный момент. Тут или дорабатывать разом, или оставлять пока так, как есть - ставишь "Нет" и очищаешь поле. Единственное, я ещё добавлю, что бы поле можно было очистить по Del.

**Comment by idzm** [comment]
Ок - оставляем пока такой вариант.
