### ISSUE TITLE
Получение справки с платформы ostis.savushkin.by

### ISSUE THREAD

**Issue by idzm** [savushkin-r-d/EasyEPLANner#443]
Необходимо предоставить пользователю получать интеллектуальную справку по основным элементам системы в контексте **S88**. Для этого предлагается по нажатии пользователем **F1** запускать браузер с адресом вида [http://ostis.savushkin.by/?sys_id=recipe](http://ostis.savushkin.by/?sys_id=recipe), где `recipe` - ключевое слово, ассоциированное с текущим активным узлом дерева представления описания проекта.

**Comment by dimabeel** [comment]
@idzm, это срочно?

**Comment by idzm** [comment]
К пятнице желательно сделать - делаем статью в Springer, поэтому желательно вставить реальные скриншоты.

**Comment by dimabeel** [comment]
@idzm , какой список ключевых слов должен быть вместо `recipe` и для каких объектов дерева? У меня нет доступа на ostis, я не могу залогиниться под своими учетными данными.

**Comment by idzm** [comment]
Пользователь будет самостоятельно вводить свои учетные данные.
