### ISSUE TITLE
Проверка на корректность описания

### ISSUE THREAD

**Issue by idzm** [savushkin-r-d/EasyEPLANner#449]
При проверке проекта также добавить на проверку на корректность запуска управляющей программы. Для этого запускать консольный скрипт: 
```
chcp 1251
..\..\spec\main.lua  -o TAP полный_путь\main.plua
```
В случае отсутствия ошибок он возвращает 0, иначе - есть ошибки. При их наличии выводить результаты выполнения в окно сообщений пользователю.
Также должна быть возможность настройки данной функциональности пользователем (возможность изменить скрипт, отключить и т.п.).

**Comment by dimabeel** [comment]
@idzm , относительный первый путь вряд-ли подойдет, неизвестно где будет лежать скрипт на рабочей станции инженера.  Он может его положить в другое место. Поэтому путь надо, скорее всего, задавать в документации.

По самому скрипту: я его выполнил и не увидел результатов работы.
![image](https://user-images.githubusercontent.com/32632640/87039718-44e30400-c1f8-11ea-9c59-996fee865675.png)
Если это результат, то он непонятен. Как его интерпретировать?

**Comment by idzm** [comment]
Скрипт надо локально запускать.

**Comment by dimabeel** [comment]
@idzm , скрипт будет запускаться с помощью `Process.Start(application, args)` и в него уже будет передаваться строка. Если запускается от имени администратора **cmd**, то она сразу находится в` c:/Windows/System32`, а если локально, то она находится в папке пользователя `C:/users/username`. 

https://www.cyberforum.ru/csharp-beginners/thread1611076.html - это решение использовать результат выполнение скрипта без промежуточного файла.

**Comment by dimabeel** [comment]
@idzm, пробовал запустить скрипт через lua.exe. Что-то не то. Не понимаю, как эти пользоваться

![image](https://user-images.githubusercontent.com/32632640/87902105-6dbd9180-ca61-11ea-9c7a-658af047fd95.png)

Видимо через lua.exe я работаю с экземпляром lua, и он консольный скрипт не будет выполнять.

**Comment by dimabeel** [comment]
@idzm , развернул получившуюся модель на более понятный вид.
![image](https://user-images.githubusercontent.com/32632640/87945146-ff9cbd00-caa8-11ea-8d4f-622b89acf088.png)

Нужно разобраться с алгоритмом работы базовой операции, которая будет главной над всеми операциями конкретных агрегатов/аппаратов. Не совсем понимаю, как оно должно работать

**Comment by dimabeel** [comment]
`lua ..\..\spec\main.lua  -o TAP -C -путь` - корректный скрипт
