### ISSUE TITLE
Добавление виртуальных устройств в список устройств

### ISSUE THREAD

**Issue by KUZMA-1989** [savushkin-r-d/EasyEPLANner#455]
В устройствах сделать отдельную вкладку VIRT и туда добавить вкладки DI_VIRT, DO_VIRT, AI_VIRT, AO_VIRT, чтоб можно было видеть список сигналов

**Comment by dimabeel** [comment]
@KUZMA-1989 , оставлять виртуальные сигналы в группах, которые соответствуют этим сигналам? DI в DI, AI в AI и др.
Например из группы DI убираем VIRT сигналы, и добавляем их в группу DI для VIRT группы? Или надо, что бы оставались в обоих группах?
То есть, получим дублирование сигналов в двух группах.

**Comment by KUZMA-1989** [comment]
@dimabeel Сейчас вообще нет в списке сигналов виртуальных
![image](https://user-images.githubusercontent.com/56631906/87042717-b624b600-c1fc-11ea-9bbd-36878bd4ef01.png)

**Comment by KUZMA-1989** [comment]
Сделай отдельные вкладки на 1-м уровне, DI_VIRT, DO_VIRT, AI_VIRT, AO_VIRT

**Comment by KUZMA-1989** [comment]
И туда их закинь

**Comment by KUZMA-1989** [comment]
Когда нажата кнопка скрывать привязанные, то прячь их
