### ISSUE TITLE
Отображение в дереве объектов только активных (заполненных) элементов

### ISSUE THREAD

**Issue by idzm** [savushkin-r-d/EasyEPLANner#499]
Необходимо реализовать возможность отображения в дереве только заполненных элементов. Должен быть элемент (кнопка) на панели инструментов, включающий\отключающий данную функциональность. Это необходимо для разгрузки дерева - меньше элементов, проще навигация.

**Comment by dimabeel** [comment]
@idzm, что мы понимаем под словом "элемент"?

**Comment by idzm** [comment]
Элемент - узел дерева, заполненный - значит у него отличное от пустого (пустая строка) значение.

**Comment by dimabeel** [comment]
ObjectListView не поддерживает скрытие элементов дерева. Можно только заменить отображаемую модель. Надо думать, что можно придумать, потому что содержать две модели не хочется.

**Comment by dimabeel** [comment]
**Задача**: скрыть пустые элементы дерева.
**Возможное решение**: Делаем копию дерева, удаляем пустые объекты. Копия делается легко через Clone.
**Проблемы**:
В - Что делать, если меняем "Базовый объект", "Базовую операцию" или любой другой элемент, который приводит к изменению количества объектов в дереве?
О - Дерево должно обработать изменения и отобразить их, если они не пустые.
В - Как это сделать?
О - Неизвестно

В - Как проследить связь между двумя деревьями, т.к через Clone связи между деревом полным и неполным нет?
О - Неизвестно

В - Как восстановить полное дерево?
О - Неизвестно
