### ISSUE TITLE
Возможность указания для оборудования более чем одного устройства

### ISSUE THREAD

**Issue by idzm** [savushkin-r-d/EasyEPLANner#507]
В настоящее время устройства указываются так:
```
prg.sterile_air_node_tank1.TE1 = prg.control_modules.TANK1TE1
```
Реализовать возможность задания группы устройств:
```
prg.sterile_air_node_tank2.TE1 = { prg.control_modules.TANK1TE1, prg.control_modules.TANK1TE2 }
```
Пользователь через пробел будет указывать группу устройств. Если устройств одно, то оно должно сохраняться по  старому механизму.

**Comment by dimabeel** [comment]
@idzm , почему мы пишем в TE1 ещё и TE2? Это неправильно.

Мы должны изменить LUA имя оборудования. Либо для группы указывать одно имя, а для одиночного типа - другое имя. Автопривязка для множественных вариантов работать не будет (мы не можем указать в defaultValue сразу несколько значений, это неправильно с точки зрения объектов), только для одиночного.

**Comment by dimabeel** [comment]
По автопривязке думаю сделать так: привязывать по дефолтному значению, а если пользователь добавил сам, то ничего не делать, потому что датчиков всегда может быть разное количество

**Comment by idzm** [comment]
Ок. Пойдёт.
