### ISSUE TITLE
Свойства, добавляемые агрегатом, должны быть обязательными для заполнения

### ISSUE THREAD

**Issue by idzm** [savushkin-r-d/EasyEPLANner#510]
Свойства, добавляемые агрегатом (в операции аппарата), должны быть обязательными для заполнения - если они не заполнены (пустые), то должно выдаваться соответствующее сообщение. Данное требование распространяется на все агрегаты.

**Comment by dimabeel** [comment]
@idzm , свойства ещё могут быть не активны, поэтому я их тоже учитывать не буду
