### ISSUE TITLE
Добавить клапана BURKERT 8694

### ISSUE THREAD

**Issue by dimabeel** [savushkin-r-d/EasyEPLANner#514]
Документация - [тык](https://www.burkert.com/en/Media/plm/MAN/MA/MA8694-ManualREV.2-EU-EN.pdf?id=MAN0000000000000001000396587ENB).
IODD файл, описание Process Data - [тык](https://www.burkert.com/en/Media/plm/SOW/SOW/8694_DeviceDescription_A03.zip?id=SOW0000000000000001000396184MLD)
Сайт изготовителя - [тык](https://www.burkert.com.ru/ru/type/8694)

Устройства - **BURKERT Type 8694 REV.2** и **BURKERT Type 8694 IO-Link B** (_Видимо одинаковые с точки зрения ПО_). Самая полная документация только на **REV.2**, работать могут в режиме **AS-i** и **IO-Link** (_два подтипа_)

**Comment by dimabeel** [comment]
Из нужного (_как для **IO-Link**, так и для **AS-i**_):
1. Какие параметры будут экспортироваться в базу каналов?
2. Какие параметры будут у устройства?
3. Как будут называться изделия?

**Comment by dimabeel** [comment]
Input - 10 byte, output - 5 byte.

**Comment by idzm** [comment]
Вот описание IO-Link - [MA8694-8791-8696-IODD-file-EU-ML.pdf](https://github.com/savushkin-r-d/EasyEPLANner/files/5327858/MA8694-8791-8696-IODD-file-EU-ML.pdf).

**Comment by dimabeel** [comment]
Подтип - VC_IOLINK.

**Comment by dimabeel** [comment]
Изделие - "BURKERT.8694"
