### ISSUE TITLE
Расширить статистику о проекте

### ISSUE THREAD

**Issue by idzm** [savushkin-r-d/EasyEPLANner#517]
В отчетную информацию о проекте добавить информацию о количестве устройств проекта (control modules) -`control_modules_total.svg`. Основывается на #150.

**Comment by dimabeel** [comment]
@idzm , какое максимальное значение, или среднее, на которое мы ориентируемся?

**Comment by idzm** [comment]
Количество устройств - 1000 штук. Возьмем такое для начала, посмотрим на последние проекты - если что, потом изменим.
