### ISSUE TITLE
Расширить статистику о проекте

### ISSUE THREAD

**Issue by idzm** [savushkin-r-d/EasyEPLANner#521]
В отчетную информацию о проекте добавить информацию об относительном количестве (в процентах от общего количества) использованных IO-Link модулей ввода\вывода (I/O modules) -`io_link_usage.svg`. Основывается на #150.

**Comment by dimabeel** [comment]
@idzm, как быть с VTUG? Пневмоостров я могу посчитать, а клапана не имеют размеров областей и по своей сути не являются IO-Link устройствами

**Comment by idzm** [comment]
Берём не устройства, а только модули ввода/вывода.
