### ISSUE TITLE
Работа с файлами проекта в UTF-8 кодировке

### ISSUE THREAD

**Issue by idzm** [savushkin-r-d/EasyEPLANner#535]
При загрузке файлов проекта учитывать их кодировку - если исходная кодировка UTF-8, значит после модификации файлы сохраняются в данной кодировке. Аналогично для кодировки cp1251.

**Comment by dimabeel** [comment]
Что делать, если проект открывается впервые и файлы ещё не созданы. Какая кодировка должна создаваться и сохраняться?

**Comment by dimabeel** [comment]
Принято сохранять в UTF-8.
