### ISSUE TITLE
Использование "заглушек" для параметров в "Доп. свойствах"

### ISSUE THREAD

**Issue by AndreyNemenkov** [savushkin-r-d/EasyEPLANner#538]
Добавить возможность использования "заглушек" для параметров в "Доп. свойствах".
Пример проблемы: 
В некоторых операциях при использовании узла перемешивания, нам необходима постоянная работа мешалки, в этом случае, мы оставляем поля "Время работы" и "Время простоя" пустыми, чтобы не добавлять "лишние" параметры, усложняющие проект, но при этом, мы сталкиваемся с тем, что в окне "Log", появляются соответствующие сообщения об ошибках, которые по сути, ими не являются.

**Comment by idzm** [comment]
Для отключения параметра пишем в значение: **`Нет`**.
