### ISSUE TITLE
Автоматическая замена устройств в полях оборудование

### ISSUE THREAD

**Issue by KUZMA-1989** [savushkin-r-d/EasyEPLANner#540]
Сделать автоматическую замену устройств в полях оборудование, когда происходит переименование устройств или копирование и вставка объектов

**Comment by dimabeel** [comment]
При копировании и вставке объектов все работает. Необходимо, чтобы устройства с новым "ОУ" и "Номер" объекта существовали, и автоматически произойдет переименовывание. Необходимо реализовать по аналогии с переименованием устройств в "Операции", чтобы ещё устройства переименовывались в "Оборудование".
