### ISSUE TITLE
Обновление функциональности устройства "Сигнальная колонна"

### ISSUE THREAD

**Issue by AlexandraNovik** [savushkin-r-d/EasyEPLANner#547]
Есть стандартные функции работы с колонной. Необходимо описание, как они работают, также описание в каких случаях какие цвета загораются. И что необходимо, если колонна отличается от стандартной (зеленый, желтый, красный, звук).

**Comment by idzm** [comment]
Сигнальная колонна будет реализована в виде устройства (control module) со своей функциональностью. @AndreiSavushkin, @KUZMA-1989 - как назвать данное устройство?

**Comment by AndreiSavushkin** [comment]
Должен задаваться тип красной лампы и звукового сигнала (выход либо постоянный либо мигающий)

**Comment by dimabeel** [comment]
Можно написать устройство HLA - сигнальная колонна с сиреной. Всегда в ней будет лампа красная и сирена. Если подтип не указан, то будет только 2 DI сигнала (на красную лампу и сирену). Это устройство будет привязываться как оборудование к юниту.
Подтипы:
1. Не указан (красная лампа + сирена) - 2 DI
2. R_Y (красная лампа + желтая лампа + сирена) - 3 DI
3. R_G (красная лампа + зеленая лампа + сирена) - 3 DI
4. R_Y_G (красная лампа + желтая лампа + зеленая лампа + сирена) - 4 DI

Потом можно будет легко добавить IO-Link сигнальную колонну. 

Над свойством типа красной лампы и звукового сигнала надо ещё подумать

**Comment by AndreiSavushkin** [comment]
DI? ГОСТ 29149-91 Цвета световой сигнализации и кнопок - в этом документе все описано. В некоторых физических устройствах мигание красной лампы заложено в непосредственно устройство (для этих устройств DO на красный канал должен быть постоянный), а для некоторых - импульсный (о чем я и просил 14.12.2020). Тоже самое касается и для звукового сигнала

**Comment by idzm** [comment]
Сигнальная колонна. Служит для уведомления оператора о событиях.
Используется три лампочки – зелёная, жёлтая, красная и сирена:
     1. Зелёный цвет – есть активная операция (связанного аппарата или агрегата).
     2. Мигающий красный цвет – авария, тревога (не подавленная). Частота мигания 2 Гц. Дополнительно включается сирена, которую можно отключить проекта (клик по значку) либо она также отключится после подтверждения тревог, пропадания аварий.
     3. Мигающий жёлтый свет – неподтверждённое сообщение. Частота мигания 0.5 Гц.

**Comment by idzm** [comment]
Поля для данного устройства:
- `M `- ручной режим;
- `ST `- состояние.
