### ISSUE TITLE
Действие "Мойка"

### ISSUE THREAD

**Issue by AndreiSavushkin** [savushkin-r-d/EasyEPLANner#551]
Необходимо переименовать узел "Мойка" в "Устройства". 
Добавить функционал:
1. Реализовать комплекты сигналов (аналогично группам при флипе клапанов). 
2. В поле "Устройства" реализовать возможность включения любого аналогового устройства (помимо насосов с частотным управление, это также является AO, VC). Реверс - только моторы с частотным управлением.
3. Поле "Частота насосов" переименовать в "Производительность" и реализовать возможность задания параметром (уже есть) или аналоговым сигналом AI (0-100%).
![изображение](https://user-images.githubusercontent.com/58879232/94120781-33a1af00-fe59-11ea-8102-b68a08be1e99.png)
Остальной функционал оставляем прежним.

**Comment by idzm** [comment]
@AndreiSavushkin по количеству значение для полей: DI и частота насосов - может быть только одно значение?

**Comment by AndreiSavushkin** [comment]
Нет. Частота - для каждого насоса может быть своя. К тому же, может быть и насос и клапан регулирующий.
