### ISSUE TITLE
Агрегат "Линия"

### ISSUE THREAD

**Issue by FedoseevYuri** [savushkin-r-d/EasyEPLANner#558]
При добавлении агрегата "Линия", появляется объект в группу агрегатов "Линия приемки", вместо того чтобы появился объект в группе агрегатов "Линия"

![image](https://user-images.githubusercontent.com/28864957/95197727-b6742380-07e2-11eb-92e9-fa7f13f36a88.png)

**Comment by dimabeel** [comment]
@FedoseevYuri , временное решение - заменить '**line_in**' в **base_tech_object** на '**line**'. Потом эти объекты будут создаваться хорошо.

**Comment by FedoseevYuri** [comment]
Временное решение работает.
