### ISSUE TITLE
Модернизация обмена сигналов

### ISSUE THREAD

**Issue by AlexandrBehunkov** [savushkin-r-d/EasyEPLANner#561]
При обмене сигналов между проектами у  объекта "Приемник" необходимо добавить следуующее:
init_gateways(remote_gateways) в function user_init()
eval_gateways(remote_gateways) в function user_eval()

**Comment by dimabeel** [comment]
@idzm , что если, отсутствует файл shared.lua, но будут вызваны эти функции, какой результат?

**Comment by idzm** [comment]
Можно часть функций вынести в системные скрипты. @rartem - что скажешь?

**Comment by dimabeel** [comment]
После беседы с @rartem были подведены определенные итоги по этому функционалу.

В файлы **main.plua** и **main.modbus_srv.lua** не предназначена автоматическая запись в виду того, что эти файлы предназначены и для пользовательского кода тоже.

Вынести в системные скрипты инициализацию **remote_gateways** можно, но это надо вычищать в зависимости от версии скриптов, файлы проектов. Потому, что если изменить все файлы проектов под новую версию скриптов, то обмен по клиентской части может не работать из-за старой версии скриптов в проектах и отсутствия нужных функций в **main.plua**. Единственное возможное хорошее решение - надо в скриптах писать обработчики, которые предотвращают повторный вызов функции в **init()** (_вызывается один раз_) и **eval()** (_вызывается циклически_).

Аналогичная проблема касается и **modbus_srv.lua**. При отсутствии **shared.lua**, автоматически сгенерированный код сервера будет ругаться, что ничего не нашел, поэтому нужно как-то обработать эту ситуацию в скриптах, чтобы автоматически включался сервер (_и предотвращался повторный вызов функции_) и в файл **modbus_srv.lua** записывался только пользовательский код.
@idzm , @AlexandrBehunkov - ваши предложения?
