### ISSUE TITLE
Обмен сигналами между контроллерами Источник->Приемник

### ISSUE THREAD

**Issue by KUZMA-1989** [savushkin-r-d/EasyEPLANner#576]
Сделать, чтоб источник был главным, т.е. писалось здесь описание. А то не понятно и не корректно получается, обратная логика
        ip = '10.216.99.130',    -- адрес удаленного контроллера
        ipemulator = '127.0.0.1',    -- адрес удаленного контроллера при эмуляции на столе
        emulation = false,    -- включение эмуляции
        cycletime = 200,    -- время ожидания между опросами контроллера
        timeout = 300,    -- таймаут для modbus клиента
        port = 10502,    -- modbus - порт удаленного контроллера
        enabled = true,    -- включить/выключить шлюз
        station = 11,    -- номер станции modbus удаленного клиента

**Comment by dimabeel** [comment]
Нет разницы что главное, что не главное. В режиме "Источник >> Приемник" - главным является проект, с которым настраивается проект. В режиме "Приемник >> Источник" - наоборот.
Единственное что я могу, это по-умолчанию переключить в режим "Приемник >> Источник".
