### ISSUE TITLE
Описание пар сигналов для межконтроллерного взаимодействия

### ISSUE THREAD

**Issue by KUZMA-1989** [savushkin-r-d/EasyEPLANner#577]
Если описал таблицу пар сигналов в источник->приемник, то она должна отобразиться зеркально, когда меняешь вкладку на приемник-источник, т.е. должны отобразиться сигналы наоборот, сейчас пустое поле отображается

**Comment by dimabeel** [comment]
@KUZMA-1989, это не наоборот, а настройка сигналов в обратном порядке.
При настройке от "**Источник >> Приемник**" ты настраиваешь сигналы, которые будут отправлены (**слева**) и те, которые будут приняты (**справа**).

То есть, в этом случае будет заполнена переменная **shared_devices** в проекте, который редактируется и remote_gateways в проекте, с которым настраивается обмен.

В обратном же порядке "**Приемник >> Источник**" ты настраиваешь сигналы, которые будут считываться (**слева**) и те, которые будут отправляться (**справа**).

То есть, будет заполнена переменная **remote_gateways** в проекте, который редактируется и **shared_devices** в проекте, с которым настраивается обмен.
