### ISSUE TITLE
Межконтроллерное взаимодействие: ошибка в настройка PAC

### ISSUE THREAD

**Issue by KUZMA-1989** [savushkin-r-d/EasyEPLANner#578]
В настройке PAC одном случае при открытии  у меня фиксированное значение IP адреса в источнике, второй раз, когда открываешь, то в приемнике
![2](https://user-images.githubusercontent.com/56631906/96122565-56743000-0efa-11eb-912d-767e59b2af4d.png)
![1](https://user-images.githubusercontent.com/56631906/96122574-57a55d00-0efa-11eb-8e72-35b076114820.png)

**Comment by dimabeel** [comment]
@KUZMA-1989 , если попереключать между собой источник-приемник не меняется?

**Comment by KUZMA-1989** [comment]
> @KUZMA-1989 , если попереключать между собой источник-приемник, адрес не меняется? Или пощелкать по именам других проектов. В источнике все IP-адреса должны быть одинаковы т.к это адреса которые будут записаны в клиенты (это адрес сервера), чтобы обращаться к серверу

Я открываю таблицу, и в зависимости, что ты первым нажмешь источник или приемник, то тот и оказывается с фиксированным адресом

**Comment by dimabeel** [comment]
Все перепроверил, нужно больше информации. При каких условиях это происходило либо воспроизвести ошибку, чтобы я видел.

Проверил при создании с нуля обмена, при редактировании существующего, в различных режимах. IP-адреса источника всегда фиксированы, а приемника - разные. На картинке действительно косяк, но не могу его воспроизвести.
