### ISSUE TITLE
Добавить автоматический выключатель с IO-Link в eplan

### ISSUE THREAD

**Issue by KUZMA-1989** [savushkin-r-d/EasyEPLANner#58]
Добавить автоматический выключатель с IO-Link в eplan, код для заказа и просмотра на сайте PXC: 2910411. Основное обозначение в eplan будет F или FA (нужно добавить оба),  доп поле 2: FA_IOLINK (доп.поле не знаю нужно оно вообще или нет). 
[um_en_cbmc_e4_iol_108147_en_00.pdf](https://github.com/savushkin-r-d/EasyEPLANner/files/4070778/um_en_cbmc_e4_iol_108147_en_00.pdf)

**Comment by dimabeel** [comment]
@KUZMA-1989, то есть, F и FA будут одинаковыми устройствами?

**Comment by KUZMA-1989** [comment]
У нас обозначается F, но F может быть и расход, но с другой стороны расход обозначается FE, значит можно просто F

**Comment by KUZMA-1989** [comment]
Тогда останавливаемся на F

**Comment by dimabeel** [comment]
Хорошо, будет F

**Comment by KUZMA-1989** [comment]
Доп поле обсуди с Димой, я не знаю надо оно или нет

**Comment by dimabeel** [comment]
Хорошо

**Comment by dimabeel** [comment]
@KUZMA-1989 , какие параметры могут быть у этого устройства?
