### ISSUE TITLE
Добавить датчик давления FESTO SPAE с IO-Link 

### ISSUE THREAD

**Issue by KUZMA-1989** [savushkin-r-d/EasyEPLANner#59]
Добавить датчик давления FESTO SPAE с IO-Link  в eplan. Основное обозначение в eplan будет PT, доп поле 2: DEV_SPAE
[100017.pdf](https://github.com/savushkin-r-d/EasyEPLANner/files/4070869/100017.pdf)
DEV_SPAE

**Comment by idzm** [comment]
Дополнительное поле оставляем как у обычного IO-Link датчика - `DST_PT_IOLINK`. Для отличия от других, в графе артикула пишем `FESTO.SPAE-P10R`.

**Comment by dimabeel** [comment]
> Дополнительное поле оставляем как у обычного **IO-Link** датчика - `DST_PT_IOLINK`. Для отличия от других в графе артикула пишем `FESTO.SPAE-P10R`.

Не `DST_PT_IOLINK`, а `PT_IOLINK`. Изделие остается прежним т.к в таком виде оно было взято с Data Portal EPLAN. Дополнительно надо сдвинуть подтип `PT_VIRT` с перечислении с **4** позиции на **3** (_нигде не использовалось, допустимо_).
