### ISSUE TITLE
Доработать базовые шаги

### ISSUE THREAD

**Issue by dimabeel** [savushkin-r-d/EasyEPLANner#628]
Нужна возможность задавать базовые шаги в состояниях "Пауза" и "Стоп" в операции.

**Comment by dimabeel** [comment]
Надо продумать этот вопрос, поскольку в нынешней реализации состояние не учитывается и предполагается, что мы всегда работаем с состоянием "**Выполнение**". Это реализовано в том числе и в скриптах, поэтому нельзя в лоб добавить поддержку состояний в базовое описание, это приведет к проблемам обработки в скриптах.

**Comment by idzm** [comment]
Предлагается добавить дополнительные поля, для указания состояния. Вот образец: 

```Lua
prg.tank_a1.steps =         --Шаги операций.
    {
    WASHING_CIP =
        {
        RUN =
            {
            MEDIUM_CHANGE = 5,
            DRAINAGE = 7,
            },
        PAUSE =
            {
            WAITING_SIGNALS = 1,
            },
        STOP =
            {
            SWITCHING_OFF_SIGNALS = 1,
            SWITCHING_OFF_DEVICES = 2,
            }
        }
    }
```

@AlexandraNovik - пойдёт такой вариант?

**Comment by AlexandraNovik** [comment]
Да, я таблицей такого вида и пользуюсь. Вопрос, если в каком-то состоянии шаги не предусмотрены?

**Comment by dimabeel** [comment]
Записи PAUSE, RUN или STOP в данном случае не будет

**Comment by AndreiSavushkin** [comment]
Реализация в таком виде привело к тому, что во множестве реализованных проектов в местах, где прописана логика работы в main, необходимо вручную изменять код!!! Реализуйте так, чтобы новый функционал не приводил к необходимости ручных правок в большом множестве действующих проектов
> ```lua
>    RUN =
>             {
>             MEDIUM_CHANGE = 5,
>             DRAINAGE = 7,
> ```
