### ISSUE TITLE
Доработка базового объекта "Линия выдачи"

### ISSUE THREAD

**Issue by idzm** [savushkin-r-d/EasyEPLANner#651]
Реализовать возможность указания в EPLANner инженером по автоматизации:
1.  клапанов подачи воды (для проталкивания продукта). Образец полученного описания в `prg.lua`:
```lua
prg.line_out_o3.water_V = O3V21 --Для одного клапана, или { O3V21, O3V22, O3V23 } для группы клапанов.
```
2.  концентратомера (для разделения продукта). Образец полученного описания в `prg.lua`:
```lua
prg.line_out_o3.QT = prg.control_modules.O3QT1
```
3. включения/выключения паузы после опустошения крайнего танка в очереди. Образец полученного описания в `prg.lua`:
```lua
prg.line_out_o3.NEED_PAUSE_AFTER_OUT_EMPTY_TANK = true
```
4. выдача линии заданного объема. Образец полученного описания в `prg.lua`:
```lua
prg.line_out_o3.USE_OUT_VOLUME = true
```

**Comment by dimabeel** [comment]
Пункты три и четыре будут добавлены в операцию OUT с удалением упоминания OUT в названии параметров.
