### ISSUE TITLE
Доработка базовой операции "Выдача" для линии

### ISSUE THREAD

**Issue by idzm** [savushkin-r-d/EasyEPLANner#652]
Реализовать возможность указания в EPLANner инженером по автоматизации:
1. дополнительные (параллельные шаги) для приёмника. Образец полученного описания в `prg.lua`:
```lua
prg.line_out_o3.steps.OUT.IN_DRAINAGE = 13
prg.line_out_o3.steps.OUT.IN_DESTINATION = 14
```

**Comment by dimabeel** [comment]
IN_DRAINAGE - в дренаж
IN_DESTINATION - в приемник
