### ISSUE TITLE
Возможность изменения типа базового объекта

### ISSUE THREAD

**Issue by dimabeel** [savushkin-r-d/EasyEPLANner#674]
Цитата:

> Функционал смены типа объекта необходимо реализовывать - тип объекта может изменяться при модернизации производства. Нужно делать в новом каком-то окне с отображением изменений, которые произойдут. Нужно максимально оставлять имеющийся функционал. Зачем же например удалять какие-либо операции? - удаляйте только тип этой базовой операции, а сама операция, шаги должна остаться.

Подумать над тем, как это правильно сделать. Были предложения, чтобы при смене базового объекта показывалось, какие объекты удаляются, какие добавляются и какие не изменяются. Объекты, которые не изменяются - не трогать (_меняется базовый владелец, типа такого_)

**Comment by dimabeel** [comment]
Этот запрос будет закрыт в несколько этапов. Первый этап - сбрасывать базовый объект в состояние "неопознанный объект".

**Comment by idzm** [comment]
На текущий момент это реализовано через сброс базового объекта (в состояние "неопознанный объект") и выбор нового.
