### ISSUE TITLE
Добавление операции "Подогрев основы" для базового аппарата

### ISSUE THREAD

**Issue by idzm** [savushkin-r-d/EasyEPLANner#700]
Lua-имя - `HEATING`.

 Для операции 2 шага
1. Нагрев - `HEATING`;
2. Проверка температуры - `CHECKING_TEMPERATURE`.

Параметры:
1. Максимальное время операции - `MAX_TIME`.

**Comment by dimabeel** [comment]
Параметры 1 и 3 будут добавлены узлами подогрева и бойлером соответственно.

**Comment by idzm** [comment]
Также необходимо добавить следующий параметр:
Время стабилизации температуры, сек - `TEMPERATURE_VERIFICATION_TIME`.
