### ISSUE TITLE
Добавление операции "Отделение сыворотки по оборотам" для базового аппарата

### ISSUE THREAD

**Issue by idzm** [savushkin-r-d/EasyEPLANner#702]
Lua-имя - `WHEY_SEPARATION_TURNOVER`.

Параметры:
1. Максимальное время операции - `MAX_TIME`.

**Comment by dimabeel** [comment]
@idzm, у нас уже есть отделение сыворотки (нагрев) - _WHEY_SEPARATION_PRE_. Надо дать наверное другое название, чтобы учитывалось что по оборотам.

**Comment by idzm** [comment]
Также необходимо добавить следующие параметры:
    1. **CURRENT_STEP** - текущий шаг, номер параметра;
    2. **STEP1_SPEED** - скорость перемешивания для шага 1 (обороты/мин), номер параметра;
    3. **STEP1_DIRECTION** - направление перемешивания для шага 1, номер параметра;
    4. **STEP1_COUNT** - количество оборотов  для шага 1, номер параметра;
    5. **STEP1_WAIT** - время ожидания после перемешивания (мин), номер параметра;
    6. **HEAT_TEMPERATURE** - температура подогрева, номер параметра.

**Comment by dimabeel** [comment]
@idzm, может быть не номер параметра надо указывать, а его имя?

**Comment by idzm** [comment]
Все правильно, поправить описание нужно.
