### ISSUE TITLE
Добавить подтип виртуального устройства для всех устройств, которые ещё не имеют такого подтипа

### ISSUE THREAD

**Issue by KUZMA-1989** [savushkin-r-d/EasyEPLANner#718]
Сделать, чтоб можно было в допсвойствах устройств аппаратов, агрегатов можно было привязывать сигналы: для дискретных устройств- привязка DI, для аналоговых устройств - AI

**Comment by KUZMA-1989** [comment]
Это расширит функционал, если мы работаем с обменом сигналами с партнерами

**Comment by dimabeel** [comment]
Для этой цели лучше использовать виртуальные устройства (нужно добавить), и передавать устройства через межпроектный обмен сигналами. На данный момент есть виртуальные устройства: FQT, LT, LS. 
Нужен список виртуальных устройств и я его добавлю. Такое взаимодействие в мойках каких-то реализовано.

@rartem будет работать же?

**Comment by rartem** [comment]
Должно работать

**Comment by dimabeel** [comment]
@KUZMA-1989, мне нужен список устройств, которые мы сделаем виртуальными, помимо FQT, LT, LS.

**Comment by KUZMA-1989** [comment]
Устройства могут быть виртуальными все,которые мы используем
