### ISSUE TITLE
Дополнительные параметры для размеров танка для датчиков LT_IOLINK

### ISSUE THREAD

**Issue by KUZMA-1989** [savushkin-r-d/EasyEPLANner#73]
Добавить варианты датчиков LT с IO-Link интерфейсом LT_IOLINK_CYL и параметры (P_MAX_P, P_R), LT_IOLINK_CONE параметры (P_MAX_P, P_R, P_H_CONE), LT_IOLINK_TRUNC параметры (P_MAX_P, P_R, P_H_TRUNC), чтоб велся автоматический пересчет в программе данных в литры продукта, реализация аналогична старым датчикам без IO-Link.

**Comment by idzm** [comment]
@KUZMA-1989 - предлагаю все эти параметры добавить в текущее устройство LT_IOLINK. Это будет проще и удобнее в использовании.

**Comment by dimabeel** [comment]
@idzm, а как тогда сигнализировать об ошибке? Если, например задано 2 параметра - это LT_IOLINK_CYL. Окей, это можно проверить. А вот если должно быть задано 3 параметра? Система не посчитает ошибку, потому что два из трех параметров будут присутствовать, и подтип будет соответствовать LT_IOLINK_CYL и инженер по АСУТП не заметит ошибки. Причем отловить это будет не так уж и легко.

**Comment by idzm** [comment]
Надо, чтобы были заданы все параметры. Те, которые не нужны для расчёта, будут иметь значение ноль - 0.

**Comment by dimabeel** [comment]
То есть, строка параметров для:
1. _LT_IOLINK_CYL:_ "P_MAX_P={**value**}, P_R={**value**}, P_H_CONE=**0**, P_H_TRUNC=**0**";
2. _LT_IOLINK_CONE_: "P_MAX_P={**value**}, P_R={**value**}, P_H_CONE={**value**}, P_H_TRUNC=**0**";
3. _LT_IOLINK_CYL_: "P_MAX_P={**value**}, P_R={**value**}, P_H_CONE=**0**, P_H_TRUNC={**value**}";

Если так, то можно. Вопрос только, понравится этот вариант @KUZMA-1989 и остальным.

**Comment by KUZMA-1989** [comment]
Так мы же сами в доп поле 3 указываем эти параметры, и в зависимости какой тип датчика указывали, те параметры и прописывали, а если какой-то отсутствовал, то появлялась ошибка. А сейчас нужно будет прописать все подряд параметры и значения указать нужные, а те, которые не нужны поставить 0 ?

**Comment by idzm** [comment]
Тип датчика также будет параметром.

**Comment by dimabeel** [comment]
Какой-то разрыв шаблона. Все датчики указывались, как и указываются, а вот для LT_IOLINK надо будет выделываться с параметрами. Если я правильно понял, то появится параметр какой-нибудь типа "TYPE=" который сможет принимать значения "CYL, CONE, TRUNC" конкретно для LT_IOLINK.

Если @idzm предлагает нечто похожее, тогда надо для всех IO-Link датчиков использовать такой вариант (если например PT_IOLINK будет иметь какие-то особенные типы, как с DEV_SPAE сейчас).

**Comment by KUZMA-1989** [comment]
У нас уже было такие устройства только без IOLINK, я хочу чтоб этот функционал работал

**Comment by KUZMA-1989** [comment]
@dimabeel Посмотри как раньше работала логика для датчиков LT

**Comment by dimabeel** [comment]
В епланере логики для датчиков нет, вся логика в управляющей программе.

**Comment by KUZMA-1989** [comment]
Тогда разбирайтесь между собой как вернуть старую логику в LT

**Comment by dimabeel** [comment]
Хорошо, в понедельник решим

**Comment by dimabeel** [comment]
@idzm , нужно решить этот вопрос как можно скорее

**Comment by idzm** [comment]
В целях упрощения предлагается такой общий тип: `LT_IOLINK_TANK`.
Cтрока параметров будет такая:
```lua
"P_MAX_P={value}, P_R={value}, P_H_CONE={value or 0}, P_H_TRUNC={value or 0}"
```

**Comment by dimabeel** [comment]
> В целях упрощения предлагается такой общий тип: `LT_IOLINK_TANK`.
> Cтрока параметров будет такая:
> 
> ```lua
> "P_MAX_P={value}, P_R={value}, P_H_CONE={value or 0}, P_H_TRUNC={value or 0}"
> ```

Лучше использовать `LT_IOLINK`, но в параметрах задавать:

`"P_MAX_P={value}, P_R={value}, P_H_CYL ={value or 0} P_H_CONE={value or 0}, P_H_TRUNC={value or 0}"`

Или же попробовать вариант без задания P_H_CYL, P_H_CONE, P_H_TRUNC, а задавать их только в случае, если это необходимо. То есть, один из этих параметров появится только если мы будем указывать какой-то определенный тип LT_IOLINK. Если задано несколько из этих параметров, то выдавать ошибку и всё

**Comment by idzm** [comment]
Так и решаем.

**Comment by idzm** [comment]
Упрощаем строку параметров:

"P_MAX_P={value}, P_R={value}, P_H_CONE={value or 0}"
