### ISSUE TITLE
Не отображается ошибка датчика температуры тип TE

### ISSUE THREAD

**Issue by KUZMA-1989** [savushkin-r-d/EasyEPLANner#74]
Не отображается ошибка датчика температуры тип TE, P_ERR. Нажимаешь обновить устройства, а eplaner не выдает ошибку, что в датчике нет такого параметра.

**Comment by dimabeel** [comment]
@KUZMA-1989, P_ERR задается автоматически. Задаваемое значение - "-1000".

**Comment by KUZMA-1989** [comment]
@dimabeel это не правильно, может быть как -1000 (охлаждение), так и 1000 (нагрев), а ошибку я все равно не вижу или ты хочешь, чтоб теплообменник взорвался, если я не увижу сообщения и будет значение -1000

**Comment by dimabeel** [comment]
@KUZMA-1989 , хорошо. Сделаю, что бы вручную задавался этот параметр
