### ISSUE TITLE
Доработка базовой операции "Наполнение" в объекте "Линия"

### ISSUE THREAD

**Issue by idzm** [savushkin-r-d/EasyEPLANner#752]
Необходимо добавить к свойствам операции **"Наполнение"** параметр, указывающий на автоматическое выключение по наполнению крайнего танка (**Lua**-имя `IS_END_ON_FULL_TANK`, пример - `prg.line1.FILL.IS_END_ON_FULL_TANK`).

**Comment by dimabeel** [comment]
@idzm параметр добавляем?

**Comment by idzm** [comment]
Да, это логический параметр, значение по умолчанию - **false**.
