### ISSUE TITLE
Ошибки при базовой операции мойка в танках

### ISSUE THREAD

**Issue by KUZMA-1989** [savushkin-r-d/EasyEPLANner#76]
При добавлении базовой операции мойка в танках появляются 2 поля с сигналами мойка свободна и мойка завершена, сейчас туда не записываются сигналы при нажатии на обозначение сигнала, только прописывать вручную, также сигналы для всех танков записываются одинаковые и при изменении меняются везде. У меня в проекте танки моются по группам 5 по одной линии, 5 по другой соответственно - данный функционал не подходит.

**Comment by dimabeel** [comment]
@KUZMA-1989, да, действительно. В ближайшее время начну работу над этим

**Comment by dimabeel** [comment]
На текущий момент будет поправлено дублирование сигналов. А по поводу добавления по кнопке - в проекте.
