### ISSUE TITLE
Механизм описания параметров базовых объектов и автоматической настройки

### ISSUE THREAD

**Issue by dimabeel** [savushkin-r-d/EasyEPLANner#766]
При вставке объекта (_нового_) автоматически нужно заполнять параметры базового объекта, если они есть. Учесть, что у объектов могут быть параметры, которые общие (_есть во всех или почти во всех объектах)_. Параметры описываем там, где описание базовых объектов.

**Comment by dimabeel** [comment]
```LUA
base_tech_objects = function()
return
    {
        automat = {
            name = "Автомат",
            s88Level = 2,
            baseOperations = { },
            basicName = "automat",
            equipment = { },
            aggregateParameters = { },
            bindingName = "automat",
            parameters =
            { 
                global_parameters.luaName,
                global_parameters.neLuaName,
            },
        }
    }
end

global_parameters =
{
    luaName = { name = "parName", luaName = "luaName" },
    neLuaName = { name = "nepar", luaName = "neLuaName" },
}
```

Предлагаю следующий формат описания параметров. Так как мы используем только **float** параметры и в редких случаях **runtime float** (_обычно МСА_), то не вижу смысла делать **runtime float**, поскольку они часто копипастятся и все. 

Такой формат позволит убрать дублирование в объектах (_можно потом распространить на все остальные аспекты, такие как параметры пид и прочее_), но появится дублирование Lua имени (_см код_), потому что при обращении к переменной **global_parameters.luaName** мы получим сразу таблицу, и никак не сможем получить имя переменной. В связи с этим, дублируется **luaName** в таблице описания параметра.

@idzm, как тебе вариант?

**Comment by idzm** [comment]
Может быть. Имя поля таблицы тоже можем получить, только зачем у нас тут два поля?

**Comment by idzm** [comment]
neLuaName - зачем это поле?

**Comment by dimabeel** [comment]
@idzm чтобы обратиться по переменной **neLuaName** в описании параметров объекта. Что-то вроде **global_parameters.neLuaName**. В итоге я получу таблицу, и не смогу получить **neLuaName**. Поэтому дублируется.

**Comment by dimabeel** [comment]
```LUA
table = {
    global_parameters.neLuaName,
    global_parameters.luaName,
}
```

тоже самое, что:
```LUA
table = {
    [ 1 ] =
    {
         luaName = "neLuaName",
        -- Опущена остальная часть
    },
   [ 2 ] =
   {
       luaName = "luaName",
       --Опущено остальное
   },
}
```
