### ISSUE TITLE
Описание базовой операции "Откачка сыворотки"

### ISSUE THREAD

**Issue by idzm** [savushkin-r-d/EasyEPLANner#776]
Необходимо добавить для аппарата описание базовой операции "Откачка сыворотки". Lua-имя - `WHEY_PUMPDOWN`. Свойства:
1. `UPPER_BUTTON`, `UPPER_STEP` - имя параметра и шаг для откачки из верхней части танка;
2. `MIDDLE_BUTTON`, `MIDDLE_STEP` - имя параметра и шаг для откачки из средней части танка;
3. `LOWER_BUTTON`, `LOWER_STEP` - имя параметра и шаг для откачки из нижней части танка.

**Comment by dimabeel** [comment]
@idzm, базовые шаги тоже надо указать. Зачем тебе параметры UPPER_STEP, MIDDLE_STEP, LOWER_STEP если мы можем просто указать базовые шаги?

**Comment by dimabeel** [comment]
Фраза "танк" тут лишняя в описании параметров и шагов. Мы редактируем объект танк, поэтому мы уже знаем, что это откачка из танка. Может написать просто "Откачка из верхней части"?

**Comment by dimabeel** [comment]
![image](https://user-images.githubusercontent.com/32632640/108810164-8ecbff00-75bb-11eb-84eb-943ef2b442a6.png)

**Comment by idzm** [comment]
> Фраза "танк" тут лишняя в описании параметров и шагов. Мы редактируем объект танк, поэтому мы уже знаем, что это откачка из танка. Может написать просто "Откачка из верхней части"?

Да, пойдёт.

**Comment by idzm** [comment]
> @idzm, базовые шаги тоже надо указать. Зачем тебе параметры UPPER_STEP, MIDDLE_STEP, LOWER_STEP если мы можем просто указать базовые шаги? Или я не так понял описание?

Параметр нужен - по его изменению мы включаем/отключаем соответстующий шаг.

**Comment by dimabeel** [comment]
Тогда и шаги нужны. Указав номер шага для операции, у которой базовая не указана - не будет сгенерировано описание

**Comment by dimabeel** [comment]
Принято решение убрать параметры и оставить только шаги.
