### ISSUE TITLE
Добавление базовой операции "Мойка" для объекта "Автомат"

### ISSUE THREAD

**Issue by idzm** [savushkin-r-d/EasyEPLANner#782]
Для объекта "Автомат" операция "Мойка" должна быть полностью идентична операции "Мойка" для объекта "Танк" (включая оборудование).

**Comment by dimabeel** [comment]
Разве у автомата есть все датчики, которые есть в танке?

**Comment by dimabeel** [comment]
Закрыто потому что линкнутый запрос был закрыт.
