### ISSUE TITLE
Возможность загрузки более одного файла описания базовых объектов

### ISSUE THREAD

**Issue by idzm** [savushkin-r-d/EasyEPLANner#791]
Файлы описания будут находится в каталоге `Lua\base_objects_description`. Их может быть несколько.

**Comment by dimabeel** [comment]
@idzm,
Предлагаю использовать название каталога - BaseObjectsDescriptionFiles.
Название стандартного файла с шаблоном, который генерируется, если файлов в каталоге нет - "**DescriptionTemplate.lua**"

**Comment by idzm** [comment]
Ок.
