### ISSUE TITLE
Добавление сведений о модулях и узлах ввода/вывода в статистику о проекте 

### ISSUE THREAD

**Issue by idzm** [savushkin-r-d/EasyEPLANner#797]
В отчётную информацию о проекте добавить информацию о количестве модулей и узлов ввода/вывода - `io_modules_total.svg` и `io_couplers_total.svg`. Основывается на #150.

Upd (by @dimabeel)
Дополнительно добавить AXC F 1152 и AXC F 3152 для определения надстройкой

**Comment by dimabeel** [comment]
@idzm, какой норматив? Сколько каплеров и модулей будет пределом?

**Comment by idzm** [comment]
Сделаем 10 и 50 соответственно.
