### ISSUE TITLE
Добавление устройства "ПИД-регулятор"

### ISSUE THREAD

**Issue by idzm** [savushkin-r-d/EasyEPLANner#810]
Необходимо добавить возможность описания устройства (control module) "ПИД-регулятор".
Тип устройства - **REGULATOR**. 

Вот  список параметров:

```C++
P_k = 1,	///< Параметр k.
P_Ti,		///< Параметр Ti.
P_Td,    	///< Параметр Td.
P_dt,   	///< Интервал расчёта, сек.

P_max, 	 ///< Мax значение входной величины.
P_min, 	 ///< Мin значение входной величины.

P_acceleration_time,	///< Время выхода на режим регулирования, сек.
P_is_manual_mode,	///< Ручной режим, 0 - авто, 1 - ручной.
P_U_manual,		///< Заданное ручное значение выходного сигнала.

P_k2,		///< Параметр k2.
P_Ti2,		///< Параметр Ti2.
P_Td2,		///< Параметр Td2. 

P_out_max,	///< Мax значение выходной величины.
P_out_min,	///< Мin значение выходной величины.

P_is_reverse,	///Обратного (реверсивного) действия, defaultValue = "false".
P_is_zero_start,///Нулевое стартовое значение, defaultValue = "true".
```
Оборудование: датчик и исполнительное устройство (control module):

```Lua
IN_VALUE = 'TE1', OUT_VALUE = 'VC1'
```

Задание задаётся в действии **"Устройства"** в **"Поле производительность"**. Это может быть параметр, либо **АI** или другой **ПИД** (control module).

**Comment by idzm** [comment]
@KUZMA-1989, @AndreiSavushkin - что скажете?

**Comment by dimabeel** [comment]
```LUA
is_reverse,        ///Обратного (реверсивного) действия", defaultValue = "false".
is_zero_start,	///Нулевое стартовое значение", defaultValue = "true".
```

Значение 0 - false
Значение 1 - true

**Comment by AndreiSavushkin** [comment]
А к чему можно привязать выход регулятора?

**Comment by dimabeel** [comment]
> А к чему можно привязать выход регулятора?

Выход регулятора привязывается к исполнительным устройствам или ко входу другого регулятора, для образования каскадного регулирования.

**Comment by AndreiSavushkin** [comment]
> 
> 
> > А к чему можно привязать выход регулятора?
> 
> Выход регулятора привязывается к исполнительным устройствам или ко входу другого регулятора, для образования каскадного регулирования.

AO?

**Comment by idzm** [comment]
Можно привязать к исполнительным устройствам (**AO**, **VC**, **M**) или ко входу другого регулятора (**R**).
