### ISSUE TITLE
Отображение ПИД-регулятора в списке устройств

### ISSUE THREAD

**Issue by KUZMA-1989** [savushkin-r-d/EasyEPLANner#818]
Надо добавить устройство "Регулятор" в список устройств и все параметры и поля вход, выход, задание с возможностью редактирования вынести туда, чтоб было легче работать с настройкой. Через доп. поля не вариант, не удобно

**Comment by idzm** [comment]
Будет реализовано при модернизации окна отображения устройств (`control modules`).
