### ISSUE TITLE
Графические файлы со статистикой о проекте не должны содержать текст

### ISSUE THREAD

**Issue by idzm** [savushkin-r-d/EasyEPLANner#819]
Графические файлы (***.svg**) со статистикой о проекте не должны содержать текст, а только численное значения параметра. Это необходимо для устранения избыточной информации при отображении статистики для группы проектов.

**Comment by dimabeel** [comment]
Принято решение для статистики для одиночных проектов указывать собственноручно названия столбцов в таблицах, тем самым, нет необходимости писать текст определяющих пункт статистики
