### ISSUE TITLE
Экспорт базы каналов

### ISSUE THREAD

**Issue by AlexandraNovik** [savushkin-r-d/EasyEPLANner#851]
Для устройств HL по умолчанию не должен экспортироваться тег P_DT, его нет в контроллере. Сейчас экспорт происходит и эти тегу приходится отключать.

**Comment by dimabeel** [comment]
Этот тег был добавлен в EasyEplanner 6 февраля 2017 года пользователем pai.
![image](https://user-images.githubusercontent.com/32632640/121303978-67980400-c904-11eb-9cd3-9b5674e8ed37.png)
Вопрос следующий, если раньше тэг был, то почему его нет сейчас? Или тэга не было все время и все предыдущие 4 года тэг отключать приходилось постоянно?

**Comment by idzm** [comment]
Данного тега нет.
