### ISSUE TITLE
Устройства Группы DI -> DO

### ISSUE THREAD

**Issue by AlexandraNovik** [savushkin-r-d/EasyEPLANner#852]
Можно было бы сделать дублирование в выходные сигналы не только DI, но и GS. 
Еще в документации среди устройств DO, для которых работает такая логика, указаны DO, SB, на самом деле еще и HL (если прописать вручную). Убирать это не нужно, но нужно обновить в документации и разрешить на добавление через дерево устройств.

**Comment by dimabeel** [comment]
Как это будет использоваться?

**Comment by AlexandraNovik** [comment]
Если горит датчик GS, то загорается выходной сигнал DO. Если GS тухнет, то тухнет и DO.
