### ISSUE TITLE
Возможность в Группе DI -> DO инвертировать сигналы

### ISSUE THREAD

**Issue by AlexandraNovik** [savushkin-r-d/EasyEPLANner#853]
Не хватает возможности при отсутствии сигнала (DI, GS, SB) включать выходные сигналы (DO, HL).

**Comment by idzm** [comment]
@AlexandraNovik - нужен конкретный пример ситуации, где нужна данная функциональность.

**Comment by AlexandraNovik** [comment]
Может быть несколько примеров.

**Comment by dimabeel** [comment]
Lua-имя: "DI_DO_Inverted"
