### ISSUE TITLE
There are no tags for lots of virtual devices

### ISSUE THREAD

**Issue by dimabeel** [savushkin-r-d/EasyEPLANner#904]
I forgot to add tags for virtual devices during #868

**Comment by dimabeel** [comment]
Improve documentation too

**Comment by dimabeel** [comment]
[tags.md](https://github.com/savushkin-r-d/EasyEPLANner/files/7120142/tags.md)

**Comment by idzm** [comment]
@dimabeel - дописал недостающие теги.
