### ISSUE TITLE
Ошибки в полях при переносе объекта из пользовательского

### ISSUE THREAD

**Issue by KUZMA-1989** [savushkin-r-d/EasyEPLANner#906]
Переводил проект BR1-Приемка из версии 2.2 на версию 2.9. Отобразились объекты из старого проекта в разделе "Пользовательский объект". Перенес их в группа агрегатов и аппаратов.
- [x]  Автоматически заполнились поля "Оборудование" в танках, но только во всех танках были привязаны устройства из первого в списке танка (у меня был это TANK16).
- [x] Для линий в объектах, тоже заполнились поля оборудование из первой в списке линии. 
- [x] Во всех объектах в параметрах, которые были привязаны к операциям, поменялись значения в поле "операция" на -1.  
- [x] Привязка добавляет + не в том месте

**Comment by dimabeel** [comment]
@KUZMA-1989 
1. В "Пользовательский объект" переход невозможен. Только в "Неопознанный объект".
2. Автоматическое заполнение оборудование предусмотрено всегда. Можно добавить ограничение, чтобы при изменении типа базового объекта этого не происходило, но тогда всегда придется записывать оборудование вручную (при изменении базового объекта)
3. По линиям - аналогично
3. Это должно было работать т.к не зависит от базовой функциональности

Какой проект? Пункт 3 я проверю, пункт 1 и 2 - так и задумано.

**Comment by KUZMA-1989** [comment]
> @KUZMA-1989
> 
> 1. В "Пользовательский объект" переход невозможен. Только в "Неопознанный объект". При условии, что перевелся проект из 2.2 в 2.9
> 2. Автоматическое заполнение оборудование предусмотрено всегда, при вставке объекта (будь то замена типа, или вставка нового объекта такого типа). Можно добавить ограничение, чтобы при изменении типа базового объекта этого не происходило, но тогда всегда придется записывать оборудование вручную (при изменении базового объекта)
> 3. По линиям - аналогично
> 4. Это должно было работать т.к не зависит от базовой функциональности
> 
> Какой проект? Пункт 3 я проверю, пункт 1 и 2 - так и задумано.

Так в поле оборудование заполнилось оборудование не из того объекта, как это так задумано?

**Comment by dimabeel** [comment]
@KUZMA-1989, не так прочитал по поводу оборудования

**Comment by dimabeel** [comment]
Подтверждено. Разбираюсь
