### ISSUE TITLE
Возможность копирования полей устройств, DI->Do и т.д.

### ISSUE THREAD

**Issue by KUZMA-1989** [savushkin-r-d/EasyEPLANner#956]
Сделать возможность копирования полей "Устройства", и всех подгрупп DI->Do и т.д. Как между объектами так и внутри объекта

**Comment by dimabeel** [comment]
@KUZMA-1989, копирование в аналогичные поля, или хочешь копировать в любое действие?

**Comment by KUZMA-1989** [comment]
> @KUZMA-1989, копирование в аналогичные поля, или хочешь копировать в любое действие?

Аналогичное в аналогичное
