### ISSUE TITLE
Сделать возможность прописывать сигналы Do в полях флипов

### ISSUE THREAD

**Issue by KUZMA-1989** [savushkin-r-d/EasyEPLANner#957]
Так как существуют ситуации для флипования микспруфов для сторонних проектов через сигналов DO , то нужно сделать возможность прописывать сигналы DO в полях флипов нижних и верхних седел

**Comment by dimabeel** [comment]
@idzm, нужна реализация в контроллере, для начала. Оттуда я возьму входные данные для реализации в EasyEplanner.
