### ISSUE TITLE
Отсутствует в Eplaner бачок лед воды

### ISSUE THREAD

**Issue by KUZMA-1989** [savushkin-r-d/EasyEPLANner#96]
При описании базового объекта отсутствует тип бачок лед воды

**Comment by dimabeel** [comment]
@KUZMA-1989 , а какие ещё "бачки" есть? Помимо обычного танка и бачка с ледяной водой?

**Comment by dimabeel** [comment]
Я бы предположил использовать префикс перед TANK. Что бы получилось типа type_TANK.
Например:
1. Бачок ледяной воды - CW_TANK (в том числе бачок откачки ледяной воды)
2. Бачок конденсата - C_TANK (В том числе бачок откачки конденсата)
3. Бачок промежуточный - IN_TANK

Остальные бачки на картинке - танки с таким названием. (со слов @idzm).

**Comment by KUZMA-1989** [comment]
@dimabeel промежуточный бачок это что?

**Comment by dimabeel** [comment]
Не знаю. Было в каком-то из проектов. Если сейчас нигде не используется, можно убрать

**Comment by KUZMA-1989** [comment]
@dimabeel  Пусть будет так

**Comment by dimabeel** [comment]
@KUZMA-1989 , хорошо, договорились.
