### ISSUE TITLE
Задание номеров шагов

### ISSUE THREAD

**Issue by AlexandraNovik** [savushkin-r-d/EasyEPLANner#987]
При задании номеров шагов в Еплан, если мы используем переход не по времени, а по состояниям устройств, возникает проблема. Если мы не задаем временные параметры для перехода в следующий шаг, то номера шагов после обновления проекта сбрасываются в -1.

**Comment by idzm** [comment]
Предлагается для решения данной проблемы расширить функциональность действия **"Проверяемые устройства"**. Добавим в него группы из пар: {следующий шаг} и {проверяемые устройства}.
